// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_accel_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln124,
        zext_ln124,
        zext_ln125,
        fm2_address0,
        fm2_ce0,
        fm2_q0,
        oc_1,
        acc_8_out,
        acc_8_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] sext_ln124;
input  [4:0] zext_ln124;
input  [4:0] zext_ln125;
output  [13:0] fm2_address0;
output   fm2_ce0;
input  [7:0] fm2_q0;
input  [4:0] oc_1;
output  [23:0] acc_8_out;
output   acc_8_out_ap_vld;

reg ap_idle;
reg acc_8_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln129_fu_234_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [12:0] c2_w_address0;
wire  signed [7:0] c2_w_q0;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] oc_1_cast_fu_185_p1;
reg   [5:0] oc_1_cast_reg_626;
wire   [6:0] zext_ln125_cast_fu_189_p1;
reg   [6:0] zext_ln125_cast_reg_631;
wire   [6:0] zext_ln124_cast_fu_193_p1;
reg   [6:0] zext_ln124_cast_reg_636;
reg   [0:0] icmp_ln129_reg_641;
reg   [0:0] icmp_ln129_reg_641_pp0_iter1_reg;
reg   [0:0] icmp_ln129_reg_641_pp0_iter2_reg;
reg   [0:0] icmp_ln129_reg_641_pp0_iter3_reg;
reg   [0:0] icmp_ln129_reg_641_pp0_iter4_reg;
wire   [0:0] icmp_ln130_fu_249_p2;
reg   [0:0] icmp_ln130_reg_645;
wire   [1:0] select_ln129_1_fu_318_p3;
reg   [1:0] select_ln129_1_reg_653;
wire   [3:0] trunc_ln130_fu_344_p1;
reg   [3:0] trunc_ln130_reg_658;
wire   [1:0] select_ln130_fu_348_p3;
reg   [1:0] select_ln130_reg_664;
wire  signed [6:0] add_ln133_1_fu_366_p2;
reg  signed [6:0] add_ln133_1_reg_669;
wire   [0:0] trunc_ln135_fu_371_p1;
reg   [0:0] trunc_ln135_reg_675;
wire   [1:0] add_ln134_fu_375_p2;
reg   [1:0] add_ln134_reg_680;
wire   [0:0] icmp_ln135_fu_466_p2;
reg   [0:0] icmp_ln135_reg_685;
wire   [63:0] zext_ln136_fu_499_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln137_3_fu_543_p1;
reg   [23:0] acc_fu_104;
wire  signed [23:0] grp_fu_574_p3;
wire  signed [23:0] sext_ln124_cast_fu_197_p1;
reg  signed [23:0] ap_sig_allocacmp_acc_load_1;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [4:0] ic_fu_108;
wire   [4:0] add_ln131_fu_381_p2;
reg   [1:0] kx_fu_112;
reg   [6:0] indvar_flatten168_fu_116;
wire   [6:0] select_ln130_1_fu_261_p3;
reg   [6:0] ap_sig_allocacmp_indvar_flatten168_load;
reg   [1:0] ky_fu_120;
reg   [7:0] indvar_flatten183_fu_124;
wire   [7:0] add_ln129_1_fu_240_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten183_load;
wire    ap_block_pp0_stage0_01001;
reg    fm2_ce0_local;
reg    c2_w_ce0_local;
wire   [6:0] add_ln130_1_fu_255_p2;
wire   [0:0] icmp_ln131_fu_306_p2;
wire   [0:0] xor_ln129_fu_301_p2;
wire   [1:0] add_ln129_fu_288_p2;
wire   [1:0] select_ln129_fu_294_p3;
wire   [0:0] and_ln129_fu_312_p2;
wire   [0:0] empty_fu_331_p2;
wire   [4:0] ic_4_mid2_fu_336_p3;
wire   [1:0] add_ln130_fu_325_p2;
wire   [1:0] add_ln133_fu_356_p2;
wire  signed [6:0] sext_ln133_fu_362_p1;
wire   [10:0] tmp_fu_412_p3;
wire   [11:0] p_shl_fu_405_p3;
wire   [11:0] zext_ln135_fu_419_p1;
wire  signed [6:0] sext_ln134_fu_438_p1;
wire  signed [6:0] add_ln134_1_fu_441_p2;
wire   [1:0] tmp_3_fu_450_p4;
wire   [1:0] tmp_2_fu_429_p4;
wire   [1:0] or_ln135_fu_460_p2;
wire   [8:0] tmp_s_fu_472_p3;
wire  signed [8:0] sext_ln135_fu_402_p1;
wire   [8:0] add_ln136_fu_479_p2;
wire   [13:0] tmp_4_fu_485_p3;
wire  signed [13:0] sext_ln135_1_fu_446_p1;
wire   [13:0] add_ln136_1_fu_493_p2;
wire   [11:0] sub_ln135_fu_423_p2;
wire   [5:0] tmp_1_fu_504_p4;
wire   [11:0] tmp5_fu_514_p3;
wire   [10:0] tmp6_fu_525_p4;
wire   [12:0] zext_ln137_2_fu_533_p1;
wire   [12:0] zext_ln137_1_fu_521_p1;
wire   [12:0] add_ln137_fu_537_p2;
wire   [7:0] iv_fu_548_p3;
wire   [7:0] grp_fu_574_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_574_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 acc_fu_104 = 24'd0;
#0 ic_fu_108 = 5'd0;
#0 kx_fu_112 = 2'd0;
#0 indvar_flatten168_fu_116 = 7'd0;
#0 ky_fu_120 = 2'd0;
#0 indvar_flatten183_fu_124 = 8'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_c2_w_ROM_1P_BRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 4608 ),
    .AddressWidth( 13 ))
c2_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(c2_w_address0),
    .ce0(c2_w_ce0_local),
    .q0(c2_w_q0)
);

cnn_accel_mac_muladd_8s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_8s_8ns_24s_24_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(c2_w_q0),
    .din1(grp_fu_574_p1),
    .din2(ap_sig_allocacmp_acc_load_1),
    .ce(1'b1),
    .dout(grp_fu_574_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_104 <= sext_ln124_cast_fu_197_p1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_fu_104 <= grp_fu_574_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_108 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ic_fu_108 <= add_ln131_fu_381_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln129_fu_234_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten168_fu_116 <= select_ln130_1_fu_261_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten168_fu_116 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln129_fu_234_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten183_fu_124 <= add_ln129_1_fu_240_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten183_fu_124 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            kx_fu_112 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            kx_fu_112 <= select_ln130_fu_348_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ky_fu_120 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ky_fu_120 <= select_ln129_1_fu_318_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln133_1_reg_669 <= add_ln133_1_fu_366_p2;
        add_ln134_reg_680 <= add_ln134_fu_375_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln129_reg_641 <= icmp_ln129_fu_234_p2;
        icmp_ln129_reg_641_pp0_iter1_reg <= icmp_ln129_reg_641;
        icmp_ln130_reg_645 <= icmp_ln130_fu_249_p2;
        oc_1_cast_reg_626[4 : 0] <= oc_1_cast_fu_185_p1[4 : 0];
        select_ln129_1_reg_653 <= select_ln129_1_fu_318_p3;
        select_ln130_reg_664 <= select_ln130_fu_348_p3;
        trunc_ln130_reg_658 <= trunc_ln130_fu_344_p1;
        trunc_ln135_reg_675 <= trunc_ln135_fu_371_p1;
        zext_ln124_cast_reg_636[4 : 0] <= zext_ln124_cast_fu_193_p1[4 : 0];
        zext_ln125_cast_reg_631[4 : 0] <= zext_ln125_cast_fu_189_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln129_reg_641_pp0_iter2_reg <= icmp_ln129_reg_641_pp0_iter1_reg;
        icmp_ln129_reg_641_pp0_iter3_reg <= icmp_ln129_reg_641_pp0_iter2_reg;
        icmp_ln129_reg_641_pp0_iter4_reg <= icmp_ln129_reg_641_pp0_iter3_reg;
        icmp_ln135_reg_685 <= icmp_ln135_fu_466_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln129_reg_641_pp0_iter4_reg == 1'd1))) begin
        acc_8_out_ap_vld = 1'b1;
    end else begin
        acc_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln129_fu_234_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_acc_load_1 = grp_fu_574_p3;
    end else begin
        ap_sig_allocacmp_acc_load_1 = acc_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten168_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten168_load = indvar_flatten168_fu_116;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten183_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten183_load = indvar_flatten183_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        c2_w_ce0_local = 1'b1;
    end else begin
        c2_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm2_ce0_local = 1'b1;
    end else begin
        fm2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_8_out = acc_fu_104;

assign add_ln129_1_fu_240_p2 = (ap_sig_allocacmp_indvar_flatten183_load + 8'd1);

assign add_ln129_fu_288_p2 = (ky_fu_120 + 2'd1);

assign add_ln130_1_fu_255_p2 = (ap_sig_allocacmp_indvar_flatten168_load + 7'd1);

assign add_ln130_fu_325_p2 = (select_ln129_fu_294_p3 + 2'd1);

assign add_ln131_fu_381_p2 = (ic_4_mid2_fu_336_p3 + 5'd1);

assign add_ln133_1_fu_366_p2 = ($signed(sext_ln133_fu_362_p1) + $signed(zext_ln124_cast_reg_636));

assign add_ln133_fu_356_p2 = ($signed(select_ln129_1_fu_318_p3) + $signed(2'd3));

assign add_ln134_1_fu_441_p2 = ($signed(sext_ln134_fu_438_p1) + $signed(zext_ln125_cast_reg_631));

assign add_ln134_fu_375_p2 = ($signed(select_ln130_fu_348_p3) + $signed(2'd3));

assign add_ln136_1_fu_493_p2 = ($signed(tmp_4_fu_485_p3) + $signed(sext_ln135_1_fu_446_p1));

assign add_ln136_fu_479_p2 = ($signed(tmp_s_fu_472_p3) + $signed(sext_ln135_fu_402_p1));

assign add_ln137_fu_537_p2 = (zext_ln137_2_fu_533_p1 + zext_ln137_1_fu_521_p1);

assign and_ln129_fu_312_p2 = (xor_ln129_fu_301_p2 & icmp_ln131_fu_306_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign c2_w_address0 = zext_ln137_3_fu_543_p1;

assign empty_fu_331_p2 = (icmp_ln130_reg_645 | and_ln129_fu_312_p2);

assign fm2_address0 = zext_ln136_fu_499_p1;

assign fm2_ce0 = fm2_ce0_local;

assign grp_fu_574_p1 = grp_fu_574_p10;

assign grp_fu_574_p10 = iv_fu_548_p3;

assign ic_4_mid2_fu_336_p3 = ((empty_fu_331_p2[0:0] == 1'b1) ? 5'd0 : ic_fu_108);

assign icmp_ln129_fu_234_p2 = ((ap_sig_allocacmp_indvar_flatten183_load == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln130_fu_249_p2 = ((ap_sig_allocacmp_indvar_flatten168_load == 7'd48) ? 1'b1 : 1'b0);

assign icmp_ln131_fu_306_p2 = ((ic_fu_108 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_466_p2 = ((or_ln135_fu_460_p2 != 2'd0) ? 1'b1 : 1'b0);

assign iv_fu_548_p3 = ((icmp_ln135_reg_685[0:0] == 1'b1) ? 8'd0 : fm2_q0);

assign oc_1_cast_fu_185_p1 = oc_1;

assign or_ln135_fu_460_p2 = (tmp_3_fu_450_p4 | tmp_2_fu_429_p4);

assign p_shl_fu_405_p3 = {{trunc_ln135_reg_675}, {11'd0}};

assign select_ln129_1_fu_318_p3 = ((icmp_ln130_reg_645[0:0] == 1'b1) ? add_ln129_fu_288_p2 : ky_fu_120);

assign select_ln129_fu_294_p3 = ((icmp_ln130_reg_645[0:0] == 1'b1) ? 2'd0 : kx_fu_112);

assign select_ln130_1_fu_261_p3 = ((icmp_ln130_fu_249_p2[0:0] == 1'b1) ? 7'd1 : add_ln130_1_fu_255_p2);

assign select_ln130_fu_348_p3 = ((and_ln129_fu_312_p2[0:0] == 1'b1) ? add_ln130_fu_325_p2 : select_ln129_fu_294_p3);

assign sext_ln124_cast_fu_197_p1 = $signed(sext_ln124);

assign sext_ln133_fu_362_p1 = $signed(add_ln133_fu_356_p2);

assign sext_ln134_fu_438_p1 = $signed(add_ln134_reg_680);

assign sext_ln135_1_fu_446_p1 = add_ln134_1_fu_441_p2;

assign sext_ln135_fu_402_p1 = add_ln133_1_reg_669;

assign sub_ln135_fu_423_p2 = (p_shl_fu_405_p3 - zext_ln135_fu_419_p1);

assign tmp5_fu_514_p3 = {{tmp_1_fu_504_p4}, {oc_1_cast_reg_626}};

assign tmp6_fu_525_p4 = {{{select_ln130_reg_664}, {trunc_ln130_reg_658}}, {5'd0}};

assign tmp_1_fu_504_p4 = {{sub_ln135_fu_423_p2[11:6]}};

assign tmp_2_fu_429_p4 = {{add_ln133_1_reg_669[6:5]}};

assign tmp_3_fu_450_p4 = {{add_ln134_1_fu_441_p2[6:5]}};

assign tmp_4_fu_485_p3 = {{add_ln136_fu_479_p2}, {5'd0}};

assign tmp_fu_412_p3 = {{select_ln129_1_reg_653}, {9'd0}};

assign tmp_s_fu_472_p3 = {{trunc_ln130_reg_658}, {5'd0}};

assign trunc_ln130_fu_344_p1 = ic_4_mid2_fu_336_p3[3:0];

assign trunc_ln135_fu_371_p1 = select_ln129_1_fu_318_p3[0:0];

assign xor_ln129_fu_301_p2 = (icmp_ln130_reg_645 ^ 1'd1);

assign zext_ln124_cast_fu_193_p1 = zext_ln124;

assign zext_ln125_cast_fu_189_p1 = zext_ln125;

assign zext_ln135_fu_419_p1 = tmp_fu_412_p3;

assign zext_ln136_fu_499_p1 = add_ln136_1_fu_493_p2;

assign zext_ln137_1_fu_521_p1 = tmp5_fu_514_p3;

assign zext_ln137_2_fu_533_p1 = tmp6_fu_525_p4;

assign zext_ln137_3_fu_543_p1 = add_ln137_fu_537_p2;

always @ (posedge ap_clk) begin
    oc_1_cast_reg_626[5] <= 1'b0;
    zext_ln125_cast_reg_631[6:5] <= 2'b00;
    zext_ln124_cast_reg_636[6:5] <= 2'b00;
end

endmodule //cnn_accel_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC
