// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_accel_cnn_accel_Pipeline_C1_KY_C1_KX (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln75,
        zext_ln75,
        ow,
        fm0_address0,
        fm0_ce0,
        fm0_q0,
        fm0_1_address0,
        fm0_1_ce0,
        fm0_1_q0,
        fm0_2_address0,
        fm0_2_ce0,
        fm0_2_q0,
        fm0_3_address0,
        fm0_3_ce0,
        fm0_3_q0,
        zext_ln74_1,
        acc_2_out,
        acc_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [12:0] sext_ln75;
input  [5:0] zext_ln75;
input  [5:0] ow;
output  [9:0] fm0_address0;
output   fm0_ce0;
input  [7:0] fm0_q0;
output  [9:0] fm0_1_address0;
output   fm0_1_ce0;
input  [7:0] fm0_1_q0;
output  [9:0] fm0_2_address0;
output   fm0_2_ce0;
input  [7:0] fm0_2_q0;
output  [9:0] fm0_3_address0;
output   fm0_3_ce0;
input  [7:0] fm0_3_q0;
input  [3:0] zext_ln74_1;
output  [18:0] acc_2_out;
output   acc_2_out_ap_vld;

reg ap_idle;
reg acc_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln80_fu_247_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] c1_w_address0;
wire  signed [7:0] c1_w_q0;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] zext_ln75_cast_fu_216_p1;
reg   [7:0] zext_ln75_cast_reg_549;
reg   [0:0] icmp_ln80_reg_554;
reg   [0:0] icmp_ln80_reg_554_pp0_iter1_reg;
reg   [0:0] icmp_ln80_reg_554_pp0_iter2_reg;
reg   [0:0] icmp_ln80_reg_554_pp0_iter3_reg;
reg   [0:0] icmp_ln80_reg_554_pp0_iter4_reg;
wire   [1:0] select_ln80_fu_277_p3;
reg   [1:0] select_ln80_reg_558;
reg   [1:0] select_ln80_reg_558_pp0_iter1_reg;
wire   [1:0] select_ln80_1_fu_285_p3;
reg   [1:0] select_ln80_1_reg_563;
reg   [1:0] select_ln80_1_reg_563_pp0_iter1_reg;
wire   [1:0] add_ln83_fu_293_p2;
reg   [1:0] add_ln83_reg_569;
wire   [6:0] add_ln84_fu_303_p2;
reg   [6:0] add_ln84_reg_574;
wire   [1:0] trunc_ln84_fu_309_p1;
reg   [1:0] trunc_ln84_reg_579;
reg   [1:0] trunc_ln84_reg_579_pp0_iter1_reg;
wire   [0:0] icmp_ln87_fu_407_p2;
reg   [0:0] icmp_ln87_reg_604;
wire   [7:0] iv_fu_460_p3;
reg  signed [7:0] iv_reg_609;
wire   [63:0] zext_ln88_fu_383_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln90_1_fu_483_p1;
reg   [18:0] acc_2_fu_100;
wire  signed [18:0] grp_fu_506_p3;
wire  signed [18:0] sext_ln75_cast_fu_220_p1;
reg  signed [18:0] ap_sig_allocacmp_acc_2_load;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [1:0] kx_fu_104;
wire   [1:0] add_ln81_fu_313_p2;
reg   [1:0] ap_sig_allocacmp_kx_load;
reg   [1:0] ky_fu_108;
reg   [1:0] ap_sig_allocacmp_ky_load;
reg   [3:0] indvar_flatten141_fu_112;
wire   [3:0] add_ln80_1_fu_253_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten141_load;
wire    ap_block_pp0_stage0_01001;
reg    fm0_ce0_local;
reg    fm0_1_ce0_local;
reg    fm0_2_ce0_local;
reg    fm0_3_ce0_local;
reg    c1_w_ce0_local;
wire   [0:0] icmp_ln81_fu_271_p2;
wire   [1:0] add_ln80_fu_265_p2;
wire   [6:0] zext_ln81_fu_299_p1;
wire   [6:0] ow_cast_fu_212_p1;
wire  signed [7:0] sext_ln83_fu_334_p1;
wire   [7:0] add_ln83_1_fu_337_p2;
wire   [5:0] trunc_ln88_fu_342_p1;
wire   [7:0] zext_ln84_fu_354_p1;
wire   [7:0] add_ln84_1_fu_357_p2;
wire   [5:0] trunc_ln8_fu_363_p4;
wire   [9:0] tmp_s_fu_346_p3;
wire  signed [9:0] sext_ln87_fu_373_p1;
wire   [9:0] add_ln88_fu_377_p2;
wire   [7:0] or_ln87_fu_391_p2;
wire   [1:0] tmp_6_fu_397_p4;
wire   [5:0] tmp_5_fu_420_p3;
wire   [7:0] p_shl_fu_413_p3;
wire   [7:0] zext_ln90_2_fu_427_p1;
wire   [7:0] tmp_fu_437_p9;
wire   [7:0] tmp_fu_437_p11;
wire   [5:0] add_ln_fu_467_p3;
wire   [7:0] zext_ln90_fu_473_p1;
wire   [7:0] sub_ln90_fu_431_p2;
wire   [7:0] add_ln90_fu_477_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_437_p1;
wire  signed [1:0] tmp_fu_437_p3;
wire  signed [1:0] tmp_fu_437_p5;
wire   [1:0] tmp_fu_437_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 acc_2_fu_100 = 19'd0;
#0 kx_fu_104 = 2'd0;
#0 ky_fu_108 = 2'd0;
#0 indvar_flatten141_fu_112 = 4'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_cnn_accel_Pipeline_C1_KY_C1_KX_c1_w_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 144 ),
    .AddressWidth( 8 ))
c1_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(c1_w_address0),
    .ce0(c1_w_ce0_local),
    .q0(c1_w_q0)
);

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_9_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 8 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_9_2_8_1_1_U7(
    .din0(fm0_q0),
    .din1(fm0_1_q0),
    .din2(fm0_2_q0),
    .din3(fm0_3_q0),
    .def(tmp_fu_437_p9),
    .sel(trunc_ln84_reg_579_pp0_iter1_reg),
    .dout(tmp_fu_437_p11)
);

cnn_accel_mac_muladd_8s_8s_19s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
mac_muladd_8s_8s_19s_19_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(c1_w_q0),
    .din1(iv_reg_609),
    .din2(ap_sig_allocacmp_acc_2_load),
    .ce(1'b1),
    .dout(grp_fu_506_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_2_fu_100 <= sext_ln75_cast_fu_220_p1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_2_fu_100 <= grp_fu_506_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_247_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten141_fu_112 <= add_ln80_1_fu_253_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten141_fu_112 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_247_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            kx_fu_104 <= add_ln81_fu_313_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kx_fu_104 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_247_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ky_fu_108 <= select_ln80_1_fu_285_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ky_fu_108 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln83_reg_569 <= add_ln83_fu_293_p2;
        add_ln84_reg_574 <= add_ln84_fu_303_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln80_reg_554 <= icmp_ln80_fu_247_p2;
        icmp_ln80_reg_554_pp0_iter1_reg <= icmp_ln80_reg_554;
        icmp_ln87_reg_604 <= icmp_ln87_fu_407_p2;
        select_ln80_1_reg_563 <= select_ln80_1_fu_285_p3;
        select_ln80_1_reg_563_pp0_iter1_reg <= select_ln80_1_reg_563;
        select_ln80_reg_558 <= select_ln80_fu_277_p3;
        select_ln80_reg_558_pp0_iter1_reg <= select_ln80_reg_558;
        trunc_ln84_reg_579 <= trunc_ln84_fu_309_p1;
        trunc_ln84_reg_579_pp0_iter1_reg <= trunc_ln84_reg_579;
        zext_ln75_cast_reg_549[5 : 0] <= zext_ln75_cast_fu_216_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln80_reg_554_pp0_iter2_reg <= icmp_ln80_reg_554_pp0_iter1_reg;
        icmp_ln80_reg_554_pp0_iter3_reg <= icmp_ln80_reg_554_pp0_iter2_reg;
        icmp_ln80_reg_554_pp0_iter4_reg <= icmp_ln80_reg_554_pp0_iter3_reg;
        iv_reg_609 <= iv_fu_460_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln80_reg_554_pp0_iter4_reg == 1'd1))) begin
        acc_2_out_ap_vld = 1'b1;
    end else begin
        acc_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_fu_247_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_acc_2_load = grp_fu_506_p3;
    end else begin
        ap_sig_allocacmp_acc_2_load = acc_2_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten141_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten141_load = indvar_flatten141_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_kx_load = 2'd0;
    end else begin
        ap_sig_allocacmp_kx_load = kx_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ky_load = 2'd0;
    end else begin
        ap_sig_allocacmp_ky_load = ky_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        c1_w_ce0_local = 1'b1;
    end else begin
        c1_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fm0_1_ce0_local = 1'b1;
    end else begin
        fm0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fm0_2_ce0_local = 1'b1;
    end else begin
        fm0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fm0_3_ce0_local = 1'b1;
    end else begin
        fm0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fm0_ce0_local = 1'b1;
    end else begin
        fm0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_2_out = acc_2_fu_100;

assign add_ln80_1_fu_253_p2 = (ap_sig_allocacmp_indvar_flatten141_load + 4'd1);

assign add_ln80_fu_265_p2 = (ap_sig_allocacmp_ky_load + 2'd1);

assign add_ln81_fu_313_p2 = (select_ln80_fu_277_p3 + 2'd1);

assign add_ln83_1_fu_337_p2 = ($signed(sext_ln83_fu_334_p1) + $signed(zext_ln75_cast_reg_549));

assign add_ln83_fu_293_p2 = (select_ln80_1_fu_285_p3 + 2'd3);

assign add_ln84_1_fu_357_p2 = ($signed(zext_ln84_fu_354_p1) + $signed(8'd255));

assign add_ln84_fu_303_p2 = (zext_ln81_fu_299_p1 + ow_cast_fu_212_p1);

assign add_ln88_fu_377_p2 = ($signed(tmp_s_fu_346_p3) + $signed(sext_ln87_fu_373_p1));

assign add_ln90_fu_477_p2 = (zext_ln90_fu_473_p1 + sub_ln90_fu_431_p2);

assign add_ln_fu_467_p3 = {{select_ln80_reg_558_pp0_iter1_reg}, {zext_ln74_1}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign c1_w_address0 = zext_ln90_1_fu_483_p1;

assign fm0_1_address0 = zext_ln88_fu_383_p1;

assign fm0_1_ce0 = fm0_1_ce0_local;

assign fm0_2_address0 = zext_ln88_fu_383_p1;

assign fm0_2_ce0 = fm0_2_ce0_local;

assign fm0_3_address0 = zext_ln88_fu_383_p1;

assign fm0_3_ce0 = fm0_3_ce0_local;

assign fm0_address0 = zext_ln88_fu_383_p1;

assign fm0_ce0 = fm0_ce0_local;

assign icmp_ln80_fu_247_p2 = ((ap_sig_allocacmp_indvar_flatten141_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_271_p2 = ((ap_sig_allocacmp_kx_load == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_407_p2 = ((tmp_6_fu_397_p4 == 2'd0) ? 1'b1 : 1'b0);

assign iv_fu_460_p3 = ((icmp_ln87_reg_604[0:0] == 1'b1) ? tmp_fu_437_p11 : 8'd0);

assign or_ln87_fu_391_p2 = (add_ln84_1_fu_357_p2 | add_ln83_1_fu_337_p2);

assign ow_cast_fu_212_p1 = ow;

assign p_shl_fu_413_p3 = {{select_ln80_1_reg_563_pp0_iter1_reg}, {6'd0}};

assign select_ln80_1_fu_285_p3 = ((icmp_ln81_fu_271_p2[0:0] == 1'b1) ? add_ln80_fu_265_p2 : ap_sig_allocacmp_ky_load);

assign select_ln80_fu_277_p3 = ((icmp_ln81_fu_271_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_kx_load);

assign sext_ln75_cast_fu_220_p1 = $signed(sext_ln75);

assign sext_ln83_fu_334_p1 = $signed(add_ln83_reg_569);

assign sext_ln87_fu_373_p1 = $signed(trunc_ln8_fu_363_p4);

assign sub_ln90_fu_431_p2 = (p_shl_fu_413_p3 - zext_ln90_2_fu_427_p1);

assign tmp_5_fu_420_p3 = {{select_ln80_1_reg_563_pp0_iter1_reg}, {4'd0}};

assign tmp_6_fu_397_p4 = {{or_ln87_fu_391_p2[7:6]}};

assign tmp_fu_437_p9 = 'bx;

assign tmp_s_fu_346_p3 = {{trunc_ln88_fu_342_p1}, {4'd0}};

assign trunc_ln84_fu_309_p1 = add_ln84_fu_303_p2[1:0];

assign trunc_ln88_fu_342_p1 = add_ln83_1_fu_337_p2[5:0];

assign trunc_ln8_fu_363_p4 = {{add_ln84_1_fu_357_p2[7:2]}};

assign zext_ln75_cast_fu_216_p1 = zext_ln75;

assign zext_ln81_fu_299_p1 = select_ln80_fu_277_p3;

assign zext_ln84_fu_354_p1 = add_ln84_reg_574;

assign zext_ln88_fu_383_p1 = add_ln88_fu_377_p2;

assign zext_ln90_1_fu_483_p1 = add_ln90_fu_477_p2;

assign zext_ln90_2_fu_427_p1 = tmp_5_fu_420_p3;

assign zext_ln90_fu_473_p1 = add_ln_fu_467_p3;

always @ (posedge ap_clk) begin
    zext_ln75_cast_reg_549[7:6] <= 2'b00;
end

endmodule //cnn_accel_cnn_accel_Pipeline_C1_KY_C1_KX
