// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_accel_cnn_accel_Pipeline_DN_OC_DN_IC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        gap_333_reload,
        gap_347_reload,
        gap_3511_reload,
        gap_3615_reload,
        gap_3719_reload,
        gap_3823_reload,
        gap_3927_reload,
        gap_4031_reload,
        gap_4135_reload,
        gap_4239_reload,
        gap_4343_reload,
        gap_4447_reload,
        gap_4551_reload,
        gap_4655_reload,
        gap_4759_reload,
        gap_4863_reload,
        gap_4967_reload,
        gap_5071_reload,
        gap_5175_reload,
        gap_5279_reload,
        gap_5383_reload,
        gap_5487_reload,
        gap_5591_reload,
        gap_5695_reload,
        gap_5799_reload,
        gap_58103_reload,
        gap_59107_reload,
        gap_60111_reload,
        gap_61115_reload,
        gap_62119_reload,
        gap_63123_reload,
        gap_64127_reload,
        p_out,
        p_out_ap_vld,
        mux_case_291135_out,
        mux_case_291135_out_ap_vld,
        mux_case_087133_out,
        mux_case_087133_out_ap_vld,
        mux_case_189131_out,
        mux_case_189131_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] gap_333_reload;
input  [31:0] gap_347_reload;
input  [31:0] gap_3511_reload;
input  [31:0] gap_3615_reload;
input  [31:0] gap_3719_reload;
input  [31:0] gap_3823_reload;
input  [31:0] gap_3927_reload;
input  [31:0] gap_4031_reload;
input  [31:0] gap_4135_reload;
input  [31:0] gap_4239_reload;
input  [31:0] gap_4343_reload;
input  [31:0] gap_4447_reload;
input  [31:0] gap_4551_reload;
input  [31:0] gap_4655_reload;
input  [31:0] gap_4759_reload;
input  [31:0] gap_4863_reload;
input  [31:0] gap_4967_reload;
input  [31:0] gap_5071_reload;
input  [31:0] gap_5175_reload;
input  [31:0] gap_5279_reload;
input  [31:0] gap_5383_reload;
input  [31:0] gap_5487_reload;
input  [31:0] gap_5591_reload;
input  [31:0] gap_5695_reload;
input  [31:0] gap_5799_reload;
input  [31:0] gap_58103_reload;
input  [31:0] gap_59107_reload;
input  [31:0] gap_60111_reload;
input  [31:0] gap_61115_reload;
input  [31:0] gap_62119_reload;
input  [31:0] gap_63123_reload;
input  [31:0] gap_64127_reload;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] mux_case_291135_out;
output   mux_case_291135_out_ap_vld;
output  [31:0] mux_case_087133_out;
output   mux_case_087133_out_ap_vld;
output  [31:0] mux_case_189131_out;
output   mux_case_189131_out_ap_vld;

reg ap_idle;
reg p_out_ap_vld;
reg mux_case_291135_out_ap_vld;
reg mux_case_087133_out_ap_vld;
reg mux_case_189131_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln191_fu_517_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] d_w_address0;
wire   [7:0] d_w_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln191_reg_1211;
reg   [0:0] icmp_ln191_reg_1211_pp0_iter1_reg;
reg   [0:0] icmp_ln191_reg_1211_pp0_iter2_reg;
reg   [0:0] icmp_ln191_reg_1211_pp0_iter3_reg;
wire   [0:0] icmp_ln193_fu_546_p2;
reg   [0:0] icmp_ln193_reg_1215;
reg   [0:0] icmp_ln193_reg_1215_pp0_iter2_reg;
reg   [0:0] icmp_ln193_reg_1215_pp0_iter3_reg;
reg   [0:0] icmp_ln193_reg_1215_pp0_iter4_reg;
wire   [0:0] first_iter_10_fu_568_p2;
reg   [0:0] first_iter_10_reg_1223;
reg   [0:0] first_iter_10_reg_1223_pp0_iter2_reg;
reg   [0:0] first_iter_10_reg_1223_pp0_iter3_reg;
reg   [0:0] first_iter_10_reg_1223_pp0_iter4_reg;
wire   [1:0] trunc_ln191_fu_574_p1;
reg   [1:0] trunc_ln191_reg_1228;
reg   [1:0] trunc_ln191_reg_1228_pp0_iter2_reg;
reg   [1:0] trunc_ln191_reg_1228_pp0_iter3_reg;
reg   [1:0] trunc_ln191_reg_1228_pp0_iter4_reg;
wire  signed [31:0] tmp_4_fu_586_p67;
reg  signed [31:0] tmp_4_reg_1233;
reg  signed [31:0] tmp_4_reg_1233_pp0_iter2_reg;
wire   [0:0] icmp_ln193_1_fu_715_p2;
reg   [0:0] icmp_ln193_1_reg_1243;
reg   [0:0] icmp_ln193_1_reg_1243_pp0_iter2_reg;
reg   [0:0] icmp_ln193_1_reg_1243_pp0_iter3_reg;
reg   [0:0] icmp_ln193_1_reg_1243_pp0_iter4_reg;
reg  signed [7:0] d_w_load_reg_1247;
wire   [31:0] grp_fu_495_p2;
reg   [31:0] mul_ln195_reg_1257;
wire   [63:0] zext_ln195_fu_704_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] acc_fu_214;
wire   [31:0] logit_fu_834_p2;
reg   [5:0] ic_fu_218;
wire   [5:0] add_ln193_fu_709_p2;
wire    ap_loop_init;
reg   [2:0] oc_fu_222;
wire   [2:0] select_ln191_5_fu_560_p3;
reg   [31:0] empty_fu_226;
wire   [31:0] select_ln191_4_fu_793_p3;
reg   [31:0] empty_35_fu_230;
wire   [31:0] select_ln191_3_fu_786_p3;
reg   [31:0] empty_36_fu_234;
wire   [31:0] select_ln191_2_fu_779_p3;
reg   [31:0] empty_37_fu_238;
wire   [31:0] select_ln191_1_fu_772_p3;
reg   [7:0] indvar_flatten300_fu_242;
wire   [7:0] add_ln191_1_fu_523_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten300_load;
reg   [31:0] mux_case_189131_fu_246;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [31:0] mux_case_087133_fu_250;
reg   [31:0] mux_case_291135_fu_254;
reg   [31:0] empty_38_fu_258;
wire    ap_block_pp0_stage0_01001;
reg    d_w_ce0_local;
wire   [2:0] add_ln191_fu_540_p2;
wire   [5:0] select_ln191_fu_552_p3;
wire   [31:0] tmp_4_fu_586_p65;
wire   [4:0] trunc_ln193_fu_582_p1;
wire   [6:0] shl_ln1_fu_690_p3;
wire   [6:0] zext_ln191_fu_578_p1;
wire   [6:0] add_ln195_fu_698_p2;
wire   [7:0] acc_1_fu_800_p9;
wire   [7:0] acc_1_fu_800_p11;
wire  signed [31:0] sext_ln192_fu_823_p1;
wire   [31:0] select_ln193_fu_827_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_4_fu_586_p1;
wire   [4:0] tmp_4_fu_586_p3;
wire   [4:0] tmp_4_fu_586_p5;
wire   [4:0] tmp_4_fu_586_p7;
wire   [4:0] tmp_4_fu_586_p9;
wire   [4:0] tmp_4_fu_586_p11;
wire   [4:0] tmp_4_fu_586_p13;
wire   [4:0] tmp_4_fu_586_p15;
wire   [4:0] tmp_4_fu_586_p17;
wire   [4:0] tmp_4_fu_586_p19;
wire   [4:0] tmp_4_fu_586_p21;
wire   [4:0] tmp_4_fu_586_p23;
wire   [4:0] tmp_4_fu_586_p25;
wire   [4:0] tmp_4_fu_586_p27;
wire   [4:0] tmp_4_fu_586_p29;
wire   [4:0] tmp_4_fu_586_p31;
wire  signed [4:0] tmp_4_fu_586_p33;
wire  signed [4:0] tmp_4_fu_586_p35;
wire  signed [4:0] tmp_4_fu_586_p37;
wire  signed [4:0] tmp_4_fu_586_p39;
wire  signed [4:0] tmp_4_fu_586_p41;
wire  signed [4:0] tmp_4_fu_586_p43;
wire  signed [4:0] tmp_4_fu_586_p45;
wire  signed [4:0] tmp_4_fu_586_p47;
wire  signed [4:0] tmp_4_fu_586_p49;
wire  signed [4:0] tmp_4_fu_586_p51;
wire  signed [4:0] tmp_4_fu_586_p53;
wire  signed [4:0] tmp_4_fu_586_p55;
wire  signed [4:0] tmp_4_fu_586_p57;
wire  signed [4:0] tmp_4_fu_586_p59;
wire  signed [4:0] tmp_4_fu_586_p61;
wire  signed [4:0] tmp_4_fu_586_p63;
wire   [1:0] acc_1_fu_800_p1;
wire   [1:0] acc_1_fu_800_p3;
wire  signed [1:0] acc_1_fu_800_p5;
wire  signed [1:0] acc_1_fu_800_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 acc_fu_214 = 32'd0;
#0 ic_fu_218 = 6'd0;
#0 oc_fu_222 = 3'd0;
#0 empty_fu_226 = 32'd0;
#0 empty_35_fu_230 = 32'd0;
#0 empty_36_fu_234 = 32'd0;
#0 empty_37_fu_238 = 32'd0;
#0 indvar_flatten300_fu_242 = 8'd0;
#0 mux_case_189131_fu_246 = 32'd0;
#0 mux_case_087133_fu_250 = 32'd0;
#0 mux_case_291135_fu_254 = 32'd0;
#0 empty_38_fu_258 = 32'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_cnn_accel_Pipeline_DN_OC_DN_IC_d_w_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
d_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(d_w_address0),
    .ce0(d_w_ce0_local),
    .q0(d_w_q0)
);

cnn_accel_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_1233_pp0_iter2_reg),
    .din1(d_w_load_reg_1247),
    .ce(1'b1),
    .dout(grp_fu_495_p2)
);

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_65_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_65_5_32_1_1_U74(
    .din0(gap_333_reload),
    .din1(gap_347_reload),
    .din2(gap_3511_reload),
    .din3(gap_3615_reload),
    .din4(gap_3719_reload),
    .din5(gap_3823_reload),
    .din6(gap_3927_reload),
    .din7(gap_4031_reload),
    .din8(gap_4135_reload),
    .din9(gap_4239_reload),
    .din10(gap_4343_reload),
    .din11(gap_4447_reload),
    .din12(gap_4551_reload),
    .din13(gap_4655_reload),
    .din14(gap_4759_reload),
    .din15(gap_4863_reload),
    .din16(gap_4967_reload),
    .din17(gap_5071_reload),
    .din18(gap_5175_reload),
    .din19(gap_5279_reload),
    .din20(gap_5383_reload),
    .din21(gap_5487_reload),
    .din22(gap_5591_reload),
    .din23(gap_5695_reload),
    .din24(gap_5799_reload),
    .din25(gap_58103_reload),
    .din26(gap_59107_reload),
    .din27(gap_60111_reload),
    .din28(gap_61115_reload),
    .din29(gap_62119_reload),
    .din30(gap_63123_reload),
    .din31(gap_64127_reload),
    .def(tmp_4_fu_586_p65),
    .sel(trunc_ln193_fu_582_p1),
    .dout(tmp_4_fu_586_p67)
);

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_9_2_8_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_9_2_8_1_1_x_U75(
    .din0(8'd6),
    .din1(8'd139),
    .din2(8'd80),
    .din3(8'd49),
    .def(acc_1_fu_800_p9),
    .sel(trunc_ln191_reg_1228_pp0_iter4_reg),
    .dout(acc_1_fu_800_p11)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd3))) begin
        empty_38_fu_258 <= logit_fu_834_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd2)))) begin
        empty_38_fu_258 <= select_ln191_1_fu_772_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_218 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ic_fu_218 <= add_ln193_fu_709_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln191_fu_517_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten300_fu_242 <= add_ln191_1_fu_523_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten300_fu_242 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd0))) begin
        mux_case_087133_fu_250 <= logit_fu_834_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd2)))) begin
        mux_case_087133_fu_250 <= select_ln191_3_fu_786_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd1))) begin
        mux_case_189131_fu_246 <= logit_fu_834_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd2)))) begin
        mux_case_189131_fu_246 <= select_ln191_4_fu_793_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd1)))) begin
        mux_case_291135_fu_254 <= select_ln191_2_fu_779_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln193_1_reg_1243_pp0_iter4_reg == 1'd1) & (trunc_ln191_reg_1228_pp0_iter4_reg == 2'd2))) begin
        mux_case_291135_fu_254 <= logit_fu_834_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oc_fu_222 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            oc_fu_222 <= select_ln191_5_fu_560_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        acc_fu_214 <= logit_fu_834_p2;
        empty_35_fu_230 <= select_ln191_3_fu_786_p3;
        empty_36_fu_234 <= select_ln191_2_fu_779_p3;
        empty_37_fu_238 <= select_ln191_1_fu_772_p3;
        empty_fu_226 <= select_ln191_4_fu_793_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_10_reg_1223 <= first_iter_10_fu_568_p2;
        icmp_ln191_reg_1211 <= icmp_ln191_fu_517_p2;
        icmp_ln191_reg_1211_pp0_iter1_reg <= icmp_ln191_reg_1211;
        icmp_ln193_1_reg_1243 <= icmp_ln193_1_fu_715_p2;
        icmp_ln193_reg_1215 <= icmp_ln193_fu_546_p2;
        tmp_4_reg_1233 <= tmp_4_fu_586_p67;
        trunc_ln191_reg_1228 <= trunc_ln191_fu_574_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        d_w_load_reg_1247 <= d_w_q0;
        first_iter_10_reg_1223_pp0_iter2_reg <= first_iter_10_reg_1223;
        first_iter_10_reg_1223_pp0_iter3_reg <= first_iter_10_reg_1223_pp0_iter2_reg;
        first_iter_10_reg_1223_pp0_iter4_reg <= first_iter_10_reg_1223_pp0_iter3_reg;
        icmp_ln191_reg_1211_pp0_iter2_reg <= icmp_ln191_reg_1211_pp0_iter1_reg;
        icmp_ln191_reg_1211_pp0_iter3_reg <= icmp_ln191_reg_1211_pp0_iter2_reg;
        icmp_ln193_1_reg_1243_pp0_iter2_reg <= icmp_ln193_1_reg_1243;
        icmp_ln193_1_reg_1243_pp0_iter3_reg <= icmp_ln193_1_reg_1243_pp0_iter2_reg;
        icmp_ln193_1_reg_1243_pp0_iter4_reg <= icmp_ln193_1_reg_1243_pp0_iter3_reg;
        icmp_ln193_reg_1215_pp0_iter2_reg <= icmp_ln193_reg_1215;
        icmp_ln193_reg_1215_pp0_iter3_reg <= icmp_ln193_reg_1215_pp0_iter2_reg;
        icmp_ln193_reg_1215_pp0_iter4_reg <= icmp_ln193_reg_1215_pp0_iter3_reg;
        mul_ln195_reg_1257 <= grp_fu_495_p2;
        tmp_4_reg_1233_pp0_iter2_reg <= tmp_4_reg_1233;
        trunc_ln191_reg_1228_pp0_iter2_reg <= trunc_ln191_reg_1228;
        trunc_ln191_reg_1228_pp0_iter3_reg <= trunc_ln191_reg_1228_pp0_iter2_reg;
        trunc_ln191_reg_1228_pp0_iter4_reg <= trunc_ln191_reg_1228_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((icmp_ln191_fu_517_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten300_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten300_load = indvar_flatten300_fu_242;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_w_ce0_local = 1'b1;
    end else begin
        d_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln191_reg_1211_pp0_iter3_reg == 1'd1))) begin
        mux_case_087133_out_ap_vld = 1'b1;
    end else begin
        mux_case_087133_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln191_reg_1211_pp0_iter3_reg == 1'd1))) begin
        mux_case_189131_out_ap_vld = 1'b1;
    end else begin
        mux_case_189131_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln191_reg_1211_pp0_iter3_reg == 1'd1))) begin
        mux_case_291135_out_ap_vld = 1'b1;
    end else begin
        mux_case_291135_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln191_reg_1211_pp0_iter3_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_800_p9 = 'bx;

assign add_ln191_1_fu_523_p2 = (ap_sig_allocacmp_indvar_flatten300_load + 8'd1);

assign add_ln191_fu_540_p2 = (oc_fu_222 + 3'd1);

assign add_ln193_fu_709_p2 = (select_ln191_fu_552_p3 + 6'd1);

assign add_ln195_fu_698_p2 = (shl_ln1_fu_690_p3 + zext_ln191_fu_578_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign d_w_address0 = zext_ln195_fu_704_p1;

assign first_iter_10_fu_568_p2 = ((select_ln191_fu_552_p3 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_517_p2 = ((ap_sig_allocacmp_indvar_flatten300_load == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln193_1_fu_715_p2 = ((add_ln193_fu_709_p2 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_546_p2 = ((ic_fu_218 == 6'd32) ? 1'b1 : 1'b0);

assign logit_fu_834_p2 = (mul_ln195_reg_1257 + select_ln193_fu_827_p3);

assign mux_case_087133_out = mux_case_087133_fu_250;

assign mux_case_189131_out = mux_case_189131_fu_246;

assign mux_case_291135_out = mux_case_291135_fu_254;

assign p_out = empty_38_fu_258;

assign select_ln191_1_fu_772_p3 = ((icmp_ln193_reg_1215_pp0_iter4_reg[0:0] == 1'b1) ? empty_38_fu_258 : empty_37_fu_238);

assign select_ln191_2_fu_779_p3 = ((icmp_ln193_reg_1215_pp0_iter4_reg[0:0] == 1'b1) ? mux_case_291135_fu_254 : empty_36_fu_234);

assign select_ln191_3_fu_786_p3 = ((icmp_ln193_reg_1215_pp0_iter4_reg[0:0] == 1'b1) ? mux_case_087133_fu_250 : empty_35_fu_230);

assign select_ln191_4_fu_793_p3 = ((icmp_ln193_reg_1215_pp0_iter4_reg[0:0] == 1'b1) ? mux_case_189131_fu_246 : empty_fu_226);

assign select_ln191_5_fu_560_p3 = ((icmp_ln193_fu_546_p2[0:0] == 1'b1) ? add_ln191_fu_540_p2 : oc_fu_222);

assign select_ln191_fu_552_p3 = ((icmp_ln193_fu_546_p2[0:0] == 1'b1) ? 6'd0 : ic_fu_218);

assign select_ln193_fu_827_p3 = ((first_iter_10_reg_1223_pp0_iter4_reg[0:0] == 1'b1) ? sext_ln192_fu_823_p1 : acc_fu_214);

assign sext_ln192_fu_823_p1 = $signed(acc_1_fu_800_p11);

assign shl_ln1_fu_690_p3 = {{trunc_ln193_fu_582_p1}, {2'd0}};

assign tmp_4_fu_586_p65 = 'bx;

assign trunc_ln191_fu_574_p1 = select_ln191_5_fu_560_p3[1:0];

assign trunc_ln193_fu_582_p1 = select_ln191_fu_552_p3[4:0];

assign zext_ln191_fu_578_p1 = select_ln191_5_fu_560_p3;

assign zext_ln195_fu_704_p1 = add_ln195_fu_698_p2;

endmodule //cnn_accel_cnn_accel_Pipeline_DN_OC_DN_IC
