// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_accel_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fm1_address0,
        fm1_ce0,
        fm1_q0,
        fm1_1_address0,
        fm1_1_ce0,
        fm1_1_q0,
        fm1_2_address0,
        fm1_2_ce0,
        fm1_2_q0,
        fm1_3_address0,
        fm1_3_ce0,
        fm1_3_q0,
        fm2_address1,
        fm2_ce1,
        fm2_we1,
        fm2_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] fm1_address0;
output   fm1_ce0;
input  [7:0] fm1_q0;
output  [13:0] fm1_1_address0;
output   fm1_1_ce0;
input  [7:0] fm1_1_q0;
output  [13:0] fm1_2_address0;
output   fm1_2_ce0;
input  [7:0] fm1_2_q0;
output  [13:0] fm1_3_address0;
output   fm1_3_ce0;
input  [7:0] fm1_3_q0;
output  [13:0] fm2_address1;
output   fm2_ce1;
output   fm2_we1;
output  [7:0] fm2_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln105_fu_185_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln106_fu_200_p2;
reg   [0:0] icmp_ln106_reg_448;
wire   [5:0] ow_1_mid2_fu_291_p3;
reg   [5:0] ow_1_mid2_reg_456;
wire   [8:0] add_ln109_fu_319_p2;
reg   [8:0] add_ln109_reg_461;
wire   [63:0] zext_ln109_2_fu_362_p1;
reg   [63:0] zext_ln109_2_reg_466;
reg   [63:0] zext_ln109_2_reg_466_pp0_iter3_reg;
wire   [7:0] m0_fu_376_p3;
reg   [7:0] m0_reg_491;
wire   [7:0] m1_fu_390_p3;
reg   [7:0] m1_reg_497;
wire    ap_block_pp0_stage0;
reg   [5:0] ow_fu_68;
wire   [5:0] add_ln107_fu_325_p2;
wire    ap_loop_init;
reg   [5:0] oh_fu_72;
wire   [5:0] select_ln106_fu_299_p3;
reg   [11:0] indvar_flatten148_fu_76;
wire   [11:0] select_ln106_1_fu_212_p3;
reg   [11:0] ap_sig_allocacmp_indvar_flatten148_load;
reg   [4:0] ic_fu_80;
wire   [4:0] select_ln105_1_fu_269_p3;
reg   [14:0] indvar_flatten161_fu_84;
wire   [14:0] add_ln105_1_fu_191_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten161_load;
reg    fm1_ce0_local;
reg    fm1_1_ce0_local;
reg    fm1_2_ce0_local;
reg    fm1_3_ce0_local;
reg    fm2_we1_local;
wire   [7:0] select_ln115_fu_402_p3;
reg    fm2_ce1_local;
wire   [11:0] add_ln106_1_fu_206_p2;
wire   [0:0] icmp_ln107_fu_257_p2;
wire   [0:0] xor_ln105_fu_252_p2;
wire   [4:0] add_ln105_fu_239_p2;
wire   [5:0] select_ln105_fu_245_p3;
wire   [0:0] and_ln105_fu_263_p2;
wire   [0:0] empty_fu_286_p2;
wire   [5:0] add_ln106_fu_280_p2;
wire   [3:0] trunc_ln106_fu_276_p1;
wire   [8:0] tmp_5_fu_307_p3;
wire   [8:0] zext_ln109_fu_315_p1;
wire   [13:0] tmp_fu_346_p3;
wire   [13:0] zext_ln109_1_fu_353_p1;
wire   [13:0] add_ln109_1_fu_356_p2;
wire   [0:0] icmp_ln113_fu_370_p2;
wire   [0:0] icmp_ln114_fu_384_p2;
wire   [0:0] icmp_ln115_fu_398_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ow_fu_68 = 6'd0;
#0 oh_fu_72 = 6'd0;
#0 indvar_flatten148_fu_76 = 12'd0;
#0 ic_fu_80 = 5'd0;
#0 indvar_flatten161_fu_84 = 15'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_80 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ic_fu_80 <= select_ln105_1_fu_269_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_185_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten148_fu_76 <= select_ln106_1_fu_212_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten148_fu_76 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_185_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten161_fu_84 <= add_ln105_1_fu_191_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten161_fu_84 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oh_fu_72 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            oh_fu_72 <= select_ln106_fu_299_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ow_fu_68 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ow_fu_68 <= add_ln107_fu_325_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln109_reg_461 <= add_ln109_fu_319_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln106_reg_448 <= icmp_ln106_fu_200_p2;
        ow_1_mid2_reg_456 <= ow_1_mid2_fu_291_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        m0_reg_491 <= m0_fu_376_p3;
        m1_reg_497 <= m1_fu_390_p3;
        zext_ln109_2_reg_466[13 : 0] <= zext_ln109_2_fu_362_p1[13 : 0];
        zext_ln109_2_reg_466_pp0_iter3_reg[13 : 0] <= zext_ln109_2_reg_466[13 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_185_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten148_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten148_load = indvar_flatten148_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten161_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten161_load = indvar_flatten161_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm1_1_ce0_local = 1'b1;
    end else begin
        fm1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm1_2_ce0_local = 1'b1;
    end else begin
        fm1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm1_3_ce0_local = 1'b1;
    end else begin
        fm1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm1_ce0_local = 1'b1;
    end else begin
        fm1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        fm2_ce1_local = 1'b1;
    end else begin
        fm2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        fm2_we1_local = 1'b1;
    end else begin
        fm2_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln105_1_fu_191_p2 = (ap_sig_allocacmp_indvar_flatten161_load + 15'd1);

assign add_ln105_fu_239_p2 = (ic_fu_80 + 5'd1);

assign add_ln106_1_fu_206_p2 = (ap_sig_allocacmp_indvar_flatten148_load + 12'd1);

assign add_ln106_fu_280_p2 = (select_ln105_fu_245_p3 + 6'd1);

assign add_ln107_fu_325_p2 = (ow_1_mid2_fu_291_p3 + 6'd1);

assign add_ln109_1_fu_356_p2 = (tmp_fu_346_p3 + zext_ln109_1_fu_353_p1);

assign add_ln109_fu_319_p2 = (tmp_5_fu_307_p3 + zext_ln109_fu_315_p1);

assign and_ln105_fu_263_p2 = (xor_ln105_fu_252_p2 & icmp_ln107_fu_257_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_286_p2 = (icmp_ln106_reg_448 | and_ln105_fu_263_p2);

assign fm1_1_address0 = zext_ln109_2_fu_362_p1;

assign fm1_1_ce0 = fm1_1_ce0_local;

assign fm1_2_address0 = zext_ln109_2_fu_362_p1;

assign fm1_2_ce0 = fm1_2_ce0_local;

assign fm1_3_address0 = zext_ln109_2_fu_362_p1;

assign fm1_3_ce0 = fm1_3_ce0_local;

assign fm1_address0 = zext_ln109_2_fu_362_p1;

assign fm1_ce0 = fm1_ce0_local;

assign fm2_address1 = zext_ln109_2_reg_466_pp0_iter3_reg;

assign fm2_ce1 = fm2_ce1_local;

assign fm2_d1 = select_ln115_fu_402_p3;

assign fm2_we1 = fm2_we1_local;

assign icmp_ln105_fu_185_p2 = ((ap_sig_allocacmp_indvar_flatten161_load == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_200_p2 = ((ap_sig_allocacmp_indvar_flatten148_load == 12'd1024) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_257_p2 = ((ow_fu_68 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_370_p2 = ((fm1_q0 > fm1_1_q0) ? 1'b1 : 1'b0);

assign icmp_ln114_fu_384_p2 = ((fm1_2_q0 > fm1_3_q0) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_398_p2 = ((m0_reg_491 > m1_reg_497) ? 1'b1 : 1'b0);

assign m0_fu_376_p3 = ((icmp_ln113_fu_370_p2[0:0] == 1'b1) ? fm1_q0 : fm1_1_q0);

assign m1_fu_390_p3 = ((icmp_ln114_fu_384_p2[0:0] == 1'b1) ? fm1_2_q0 : fm1_3_q0);

assign ow_1_mid2_fu_291_p3 = ((empty_fu_286_p2[0:0] == 1'b1) ? 6'd0 : ow_fu_68);

assign select_ln105_1_fu_269_p3 = ((icmp_ln106_reg_448[0:0] == 1'b1) ? add_ln105_fu_239_p2 : ic_fu_80);

assign select_ln105_fu_245_p3 = ((icmp_ln106_reg_448[0:0] == 1'b1) ? 6'd0 : oh_fu_72);

assign select_ln106_1_fu_212_p3 = ((icmp_ln106_fu_200_p2[0:0] == 1'b1) ? 12'd1 : add_ln106_1_fu_206_p2);

assign select_ln106_fu_299_p3 = ((and_ln105_fu_263_p2[0:0] == 1'b1) ? add_ln106_fu_280_p2 : select_ln105_fu_245_p3);

assign select_ln115_fu_402_p3 = ((icmp_ln115_fu_398_p2[0:0] == 1'b1) ? m0_reg_491 : m1_reg_497);

assign tmp_5_fu_307_p3 = {{trunc_ln106_fu_276_p1}, {5'd0}};

assign tmp_fu_346_p3 = {{add_ln109_reg_461}, {5'd0}};

assign trunc_ln106_fu_276_p1 = select_ln105_1_fu_269_p3[3:0];

assign xor_ln105_fu_252_p2 = (icmp_ln106_reg_448 ^ 1'd1);

assign zext_ln109_1_fu_353_p1 = ow_1_mid2_reg_456;

assign zext_ln109_2_fu_362_p1 = add_ln109_1_fu_356_p2;

assign zext_ln109_fu_315_p1 = select_ln106_fu_299_p3;

always @ (posedge ap_clk) begin
    zext_ln109_2_reg_466[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln109_2_reg_466_pp0_iter3_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW
