// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module cnn_accel_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_c2_w_ROM_1P_BRAM_1R (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 13;
parameter AddressRange = 4608;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
(* rom_style = "block" *)reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./cnn_accel_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_c2_w_ROM_1P_BRAM_1R.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

