// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_accel_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fm3_address0,
        fm3_ce0,
        fm3_q0,
        fm3_1_address0,
        fm3_1_ce0,
        fm3_1_q0,
        fm3_2_address0,
        fm3_2_ce0,
        fm3_2_q0,
        fm3_3_address0,
        fm3_3_ce0,
        fm3_3_q0,
        fm4_address1,
        fm4_ce1,
        fm4_we1,
        fm4_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] fm3_address0;
output   fm3_ce0;
input  [7:0] fm3_q0;
output  [12:0] fm3_1_address0;
output   fm3_1_ce0;
input  [7:0] fm3_1_q0;
output  [12:0] fm3_2_address0;
output   fm3_2_ce0;
input  [7:0] fm3_2_q0;
output  [12:0] fm3_3_address0;
output   fm3_3_ce0;
input  [7:0] fm3_3_q0;
output  [12:0] fm4_address1;
output   fm4_ce1;
output   fm4_we1;
output  [7:0] fm4_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln153_fu_187_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln154_fu_202_p2;
reg   [0:0] icmp_ln154_reg_450;
wire   [4:0] ow_3_mid2_fu_293_p3;
reg   [4:0] ow_3_mid2_reg_458;
wire   [8:0] add_ln157_fu_321_p2;
reg   [8:0] add_ln157_reg_463;
wire   [63:0] zext_ln157_2_fu_364_p1;
reg   [63:0] zext_ln157_2_reg_468;
reg   [63:0] zext_ln157_2_reg_468_pp0_iter3_reg;
wire   [7:0] m0_fu_378_p3;
reg   [7:0] m0_reg_493;
wire   [7:0] m1_fu_392_p3;
reg   [7:0] m1_reg_499;
wire    ap_block_pp0_stage0;
reg   [4:0] ow_fu_70;
wire   [4:0] add_ln155_fu_327_p2;
wire    ap_loop_init;
reg   [4:0] oh_fu_74;
wire   [4:0] select_ln154_fu_301_p3;
reg   [9:0] indvar_flatten190_fu_78;
wire   [9:0] select_ln154_1_fu_214_p3;
reg   [9:0] ap_sig_allocacmp_indvar_flatten190_load;
reg   [5:0] ic_fu_82;
wire   [5:0] select_ln153_1_fu_271_p3;
reg   [13:0] indvar_flatten203_fu_86;
wire   [13:0] add_ln153_1_fu_193_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten203_load;
reg    fm3_ce0_local;
reg    fm3_1_ce0_local;
reg    fm3_2_ce0_local;
reg    fm3_3_ce0_local;
reg    fm4_we1_local;
wire   [7:0] select_ln163_fu_404_p3;
reg    fm4_ce1_local;
wire   [9:0] add_ln154_1_fu_208_p2;
wire   [0:0] icmp_ln155_fu_259_p2;
wire   [0:0] xor_ln153_fu_254_p2;
wire   [5:0] add_ln153_fu_241_p2;
wire   [4:0] select_ln153_fu_247_p3;
wire   [0:0] and_ln153_fu_265_p2;
wire   [0:0] empty_fu_288_p2;
wire   [4:0] add_ln154_fu_282_p2;
wire   [4:0] trunc_ln154_fu_278_p1;
wire   [8:0] tmp_9_fu_309_p3;
wire   [8:0] zext_ln157_fu_317_p1;
wire   [12:0] tmp_fu_348_p3;
wire   [12:0] zext_ln157_1_fu_355_p1;
wire   [12:0] add_ln157_1_fu_358_p2;
wire   [0:0] icmp_ln161_fu_372_p2;
wire   [0:0] icmp_ln162_fu_386_p2;
wire   [0:0] icmp_ln163_fu_400_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ow_fu_70 = 5'd0;
#0 oh_fu_74 = 5'd0;
#0 indvar_flatten190_fu_78 = 10'd0;
#0 ic_fu_82 = 6'd0;
#0 indvar_flatten203_fu_86 = 14'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_82 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ic_fu_82 <= select_ln153_1_fu_271_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten190_fu_78 <= select_ln154_1_fu_214_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten190_fu_78 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten203_fu_86 <= add_ln153_1_fu_193_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten203_fu_86 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oh_fu_74 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            oh_fu_74 <= select_ln154_fu_301_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ow_fu_70 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ow_fu_70 <= add_ln155_fu_327_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln157_reg_463 <= add_ln157_fu_321_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln154_reg_450 <= icmp_ln154_fu_202_p2;
        ow_3_mid2_reg_458 <= ow_3_mid2_fu_293_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        m0_reg_493 <= m0_fu_378_p3;
        m1_reg_499 <= m1_fu_392_p3;
        zext_ln157_2_reg_468[12 : 0] <= zext_ln157_2_fu_364_p1[12 : 0];
        zext_ln157_2_reg_468_pp0_iter3_reg[12 : 0] <= zext_ln157_2_reg_468[12 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln153_fu_187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten190_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten190_load = indvar_flatten190_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten203_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten203_load = indvar_flatten203_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm3_1_ce0_local = 1'b1;
    end else begin
        fm3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm3_2_ce0_local = 1'b1;
    end else begin
        fm3_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm3_3_ce0_local = 1'b1;
    end else begin
        fm3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fm3_ce0_local = 1'b1;
    end else begin
        fm3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        fm4_ce1_local = 1'b1;
    end else begin
        fm4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        fm4_we1_local = 1'b1;
    end else begin
        fm4_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln153_1_fu_193_p2 = (ap_sig_allocacmp_indvar_flatten203_load + 14'd1);

assign add_ln153_fu_241_p2 = (ic_fu_82 + 6'd1);

assign add_ln154_1_fu_208_p2 = (ap_sig_allocacmp_indvar_flatten190_load + 10'd1);

assign add_ln154_fu_282_p2 = (select_ln153_fu_247_p3 + 5'd1);

assign add_ln155_fu_327_p2 = (ow_3_mid2_fu_293_p3 + 5'd1);

assign add_ln157_1_fu_358_p2 = (tmp_fu_348_p3 + zext_ln157_1_fu_355_p1);

assign add_ln157_fu_321_p2 = (tmp_9_fu_309_p3 + zext_ln157_fu_317_p1);

assign and_ln153_fu_265_p2 = (xor_ln153_fu_254_p2 & icmp_ln155_fu_259_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_288_p2 = (icmp_ln154_reg_450 | and_ln153_fu_265_p2);

assign fm3_1_address0 = zext_ln157_2_fu_364_p1;

assign fm3_1_ce0 = fm3_1_ce0_local;

assign fm3_2_address0 = zext_ln157_2_fu_364_p1;

assign fm3_2_ce0 = fm3_2_ce0_local;

assign fm3_3_address0 = zext_ln157_2_fu_364_p1;

assign fm3_3_ce0 = fm3_3_ce0_local;

assign fm3_address0 = zext_ln157_2_fu_364_p1;

assign fm3_ce0 = fm3_ce0_local;

assign fm4_address1 = zext_ln157_2_reg_468_pp0_iter3_reg;

assign fm4_ce1 = fm4_ce1_local;

assign fm4_d1 = select_ln163_fu_404_p3;

assign fm4_we1 = fm4_we1_local;

assign icmp_ln153_fu_187_p2 = ((ap_sig_allocacmp_indvar_flatten203_load == 14'd8192) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_202_p2 = ((ap_sig_allocacmp_indvar_flatten190_load == 10'd256) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_259_p2 = ((ow_fu_70 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln161_fu_372_p2 = ((fm3_q0 > fm3_1_q0) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_386_p2 = ((fm3_2_q0 > fm3_3_q0) ? 1'b1 : 1'b0);

assign icmp_ln163_fu_400_p2 = ((m0_reg_493 > m1_reg_499) ? 1'b1 : 1'b0);

assign m0_fu_378_p3 = ((icmp_ln161_fu_372_p2[0:0] == 1'b1) ? fm3_q0 : fm3_1_q0);

assign m1_fu_392_p3 = ((icmp_ln162_fu_386_p2[0:0] == 1'b1) ? fm3_2_q0 : fm3_3_q0);

assign ow_3_mid2_fu_293_p3 = ((empty_fu_288_p2[0:0] == 1'b1) ? 5'd0 : ow_fu_70);

assign select_ln153_1_fu_271_p3 = ((icmp_ln154_reg_450[0:0] == 1'b1) ? add_ln153_fu_241_p2 : ic_fu_82);

assign select_ln153_fu_247_p3 = ((icmp_ln154_reg_450[0:0] == 1'b1) ? 5'd0 : oh_fu_74);

assign select_ln154_1_fu_214_p3 = ((icmp_ln154_fu_202_p2[0:0] == 1'b1) ? 10'd1 : add_ln154_1_fu_208_p2);

assign select_ln154_fu_301_p3 = ((and_ln153_fu_265_p2[0:0] == 1'b1) ? add_ln154_fu_282_p2 : select_ln153_fu_247_p3);

assign select_ln163_fu_404_p3 = ((icmp_ln163_fu_400_p2[0:0] == 1'b1) ? m0_reg_493 : m1_reg_499);

assign tmp_9_fu_309_p3 = {{trunc_ln154_fu_278_p1}, {4'd0}};

assign tmp_fu_348_p3 = {{add_ln157_reg_463}, {4'd0}};

assign trunc_ln154_fu_278_p1 = select_ln153_1_fu_271_p3[4:0];

assign xor_ln153_fu_254_p2 = (icmp_ln154_reg_450 ^ 1'd1);

assign zext_ln157_1_fu_355_p1 = ow_3_mid2_reg_458;

assign zext_ln157_2_fu_364_p1 = add_ln157_1_fu_358_p2;

assign zext_ln157_fu_317_p1 = select_ln154_fu_301_p3;

always @ (posedge ap_clk) begin
    zext_ln157_2_reg_468[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
    zext_ln157_2_reg_468_pp0_iter3_reg[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW
