// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnn_accel_cnn_accel,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.404000,HLS_SYN_LAT=6329660,HLS_SYN_TPT=none,HLS_SYN_MEM=70,HLS_SYN_DSP=0,HLS_SYN_FF=5037,HLS_SYN_LUT=6131,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_accel (
        ap_clk,
        ap_rst_n,
        m_axi_MBUS_AWVALID,
        m_axi_MBUS_AWREADY,
        m_axi_MBUS_AWADDR,
        m_axi_MBUS_AWID,
        m_axi_MBUS_AWLEN,
        m_axi_MBUS_AWSIZE,
        m_axi_MBUS_AWBURST,
        m_axi_MBUS_AWLOCK,
        m_axi_MBUS_AWCACHE,
        m_axi_MBUS_AWPROT,
        m_axi_MBUS_AWQOS,
        m_axi_MBUS_AWREGION,
        m_axi_MBUS_AWUSER,
        m_axi_MBUS_WVALID,
        m_axi_MBUS_WREADY,
        m_axi_MBUS_WDATA,
        m_axi_MBUS_WSTRB,
        m_axi_MBUS_WLAST,
        m_axi_MBUS_WID,
        m_axi_MBUS_WUSER,
        m_axi_MBUS_ARVALID,
        m_axi_MBUS_ARREADY,
        m_axi_MBUS_ARADDR,
        m_axi_MBUS_ARID,
        m_axi_MBUS_ARLEN,
        m_axi_MBUS_ARSIZE,
        m_axi_MBUS_ARBURST,
        m_axi_MBUS_ARLOCK,
        m_axi_MBUS_ARCACHE,
        m_axi_MBUS_ARPROT,
        m_axi_MBUS_ARQOS,
        m_axi_MBUS_ARREGION,
        m_axi_MBUS_ARUSER,
        m_axi_MBUS_RVALID,
        m_axi_MBUS_RREADY,
        m_axi_MBUS_RDATA,
        m_axi_MBUS_RLAST,
        m_axi_MBUS_RID,
        m_axi_MBUS_RUSER,
        m_axi_MBUS_RRESP,
        m_axi_MBUS_BVALID,
        m_axi_MBUS_BREADY,
        m_axi_MBUS_BRESP,
        m_axi_MBUS_BID,
        m_axi_MBUS_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 31'd1;
parameter    ap_ST_fsm_state2 = 31'd2;
parameter    ap_ST_fsm_state3 = 31'd4;
parameter    ap_ST_fsm_state4 = 31'd8;
parameter    ap_ST_fsm_state5 = 31'd16;
parameter    ap_ST_fsm_state6 = 31'd32;
parameter    ap_ST_fsm_state7 = 31'd64;
parameter    ap_ST_fsm_state8 = 31'd128;
parameter    ap_ST_fsm_state9 = 31'd256;
parameter    ap_ST_fsm_state10 = 31'd512;
parameter    ap_ST_fsm_state11 = 31'd1024;
parameter    ap_ST_fsm_state12 = 31'd2048;
parameter    ap_ST_fsm_state13 = 31'd4096;
parameter    ap_ST_fsm_state14 = 31'd8192;
parameter    ap_ST_fsm_state15 = 31'd16384;
parameter    ap_ST_fsm_state16 = 31'd32768;
parameter    ap_ST_fsm_state17 = 31'd65536;
parameter    ap_ST_fsm_state18 = 31'd131072;
parameter    ap_ST_fsm_state19 = 31'd262144;
parameter    ap_ST_fsm_state20 = 31'd524288;
parameter    ap_ST_fsm_state21 = 31'd1048576;
parameter    ap_ST_fsm_state22 = 31'd2097152;
parameter    ap_ST_fsm_state23 = 31'd4194304;
parameter    ap_ST_fsm_state24 = 31'd8388608;
parameter    ap_ST_fsm_state25 = 31'd16777216;
parameter    ap_ST_fsm_state26 = 31'd33554432;
parameter    ap_ST_fsm_state27 = 31'd67108864;
parameter    ap_ST_fsm_state28 = 31'd134217728;
parameter    ap_ST_fsm_state29 = 31'd268435456;
parameter    ap_ST_fsm_state30 = 31'd536870912;
parameter    ap_ST_fsm_state31 = 31'd1073741824;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_M_AXI_MBUS_ID_WIDTH = 1;
parameter    C_M_AXI_MBUS_ADDR_WIDTH = 64;
parameter    C_M_AXI_MBUS_DATA_WIDTH = 32;
parameter    C_M_AXI_MBUS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MBUS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MBUS_WUSER_WIDTH = 1;
parameter    C_M_AXI_MBUS_RUSER_WIDTH = 1;
parameter    C_M_AXI_MBUS_BUSER_WIDTH = 1;
parameter    C_M_AXI_MBUS_USER_VALUE = 0;
parameter    C_M_AXI_MBUS_PROT_VALUE = 0;
parameter    C_M_AXI_MBUS_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MBUS_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_MBUS_AWVALID;
input   m_axi_MBUS_AWREADY;
output  [C_M_AXI_MBUS_ADDR_WIDTH - 1:0] m_axi_MBUS_AWADDR;
output  [C_M_AXI_MBUS_ID_WIDTH - 1:0] m_axi_MBUS_AWID;
output  [7:0] m_axi_MBUS_AWLEN;
output  [2:0] m_axi_MBUS_AWSIZE;
output  [1:0] m_axi_MBUS_AWBURST;
output  [1:0] m_axi_MBUS_AWLOCK;
output  [3:0] m_axi_MBUS_AWCACHE;
output  [2:0] m_axi_MBUS_AWPROT;
output  [3:0] m_axi_MBUS_AWQOS;
output  [3:0] m_axi_MBUS_AWREGION;
output  [C_M_AXI_MBUS_AWUSER_WIDTH - 1:0] m_axi_MBUS_AWUSER;
output   m_axi_MBUS_WVALID;
input   m_axi_MBUS_WREADY;
output  [C_M_AXI_MBUS_DATA_WIDTH - 1:0] m_axi_MBUS_WDATA;
output  [C_M_AXI_MBUS_WSTRB_WIDTH - 1:0] m_axi_MBUS_WSTRB;
output   m_axi_MBUS_WLAST;
output  [C_M_AXI_MBUS_ID_WIDTH - 1:0] m_axi_MBUS_WID;
output  [C_M_AXI_MBUS_WUSER_WIDTH - 1:0] m_axi_MBUS_WUSER;
output   m_axi_MBUS_ARVALID;
input   m_axi_MBUS_ARREADY;
output  [C_M_AXI_MBUS_ADDR_WIDTH - 1:0] m_axi_MBUS_ARADDR;
output  [C_M_AXI_MBUS_ID_WIDTH - 1:0] m_axi_MBUS_ARID;
output  [7:0] m_axi_MBUS_ARLEN;
output  [2:0] m_axi_MBUS_ARSIZE;
output  [1:0] m_axi_MBUS_ARBURST;
output  [1:0] m_axi_MBUS_ARLOCK;
output  [3:0] m_axi_MBUS_ARCACHE;
output  [2:0] m_axi_MBUS_ARPROT;
output  [3:0] m_axi_MBUS_ARQOS;
output  [3:0] m_axi_MBUS_ARREGION;
output  [C_M_AXI_MBUS_ARUSER_WIDTH - 1:0] m_axi_MBUS_ARUSER;
input   m_axi_MBUS_RVALID;
output   m_axi_MBUS_RREADY;
input  [C_M_AXI_MBUS_DATA_WIDTH - 1:0] m_axi_MBUS_RDATA;
input   m_axi_MBUS_RLAST;
input  [C_M_AXI_MBUS_ID_WIDTH - 1:0] m_axi_MBUS_RID;
input  [C_M_AXI_MBUS_RUSER_WIDTH - 1:0] m_axi_MBUS_RUSER;
input  [1:0] m_axi_MBUS_RRESP;
input   m_axi_MBUS_BVALID;
output   m_axi_MBUS_BREADY;
input  [1:0] m_axi_MBUS_BRESP;
input  [C_M_AXI_MBUS_ID_WIDTH - 1:0] m_axi_MBUS_BID;
input  [C_M_AXI_MBUS_BUSER_WIDTH - 1:0] m_axi_MBUS_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] in_bram;
wire   [7:0] cls_out;
reg    cls_out_ap_vld;
wire   [3:0] c1_b_address0;
wire   [12:0] c1_b_q0;
wire   [4:0] c2_b_address0;
wire   [11:0] c2_b_q0;
reg    MBUS_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [61:0] trunc_ln_reg_1560;
wire   [4:0] add_ln74_fu_773_p2;
reg   [4:0] add_ln74_reg_1574;
wire    ap_CS_fsm_state12;
wire   [3:0] trunc_ln74_fu_779_p1;
reg   [3:0] trunc_ln74_reg_1579;
reg   [12:0] acc_reg_1597;
wire    ap_CS_fsm_state13;
wire   [6:0] add_ln75_fu_799_p2;
reg   [6:0] add_ln75_reg_1605;
wire    ap_CS_fsm_state14;
wire   [5:0] trunc_ln75_fu_805_p1;
reg   [5:0] trunc_ln75_reg_1610;
wire   [0:0] trunc_ln75_1_fu_809_p1;
reg   [0:0] trunc_ln75_1_reg_1615;
wire   [6:0] add_ln76_fu_823_p2;
reg   [6:0] add_ln76_reg_1622;
wire    ap_CS_fsm_state15;
wire   [5:0] trunc_ln76_fu_829_p1;
reg   [5:0] trunc_ln76_reg_1627;
wire   [0:0] trunc_ln76_1_fu_834_p1;
reg   [0:0] trunc_ln76_1_reg_1632;
reg   [4:0] lshr_ln3_reg_1636;
reg   [4:0] tmp_reg_1641;
wire   [5:0] add_ln123_fu_953_p2;
reg   [5:0] add_ln123_reg_1649;
wire    ap_CS_fsm_state19;
wire   [4:0] trunc_ln123_fu_959_p1;
reg   [4:0] trunc_ln123_reg_1654;
reg   [11:0] acc_5_reg_1665;
wire    ap_CS_fsm_state20;
wire   [5:0] add_ln124_fu_974_p2;
reg   [5:0] add_ln124_reg_1673;
wire    ap_CS_fsm_state21;
wire   [4:0] trunc_ln124_fu_980_p1;
reg   [4:0] trunc_ln124_reg_1678;
wire   [0:0] trunc_ln124_1_fu_984_p1;
reg   [0:0] trunc_ln124_1_reg_1683;
wire   [5:0] add_ln125_fu_998_p2;
reg   [5:0] add_ln125_reg_1690;
wire    ap_CS_fsm_state22;
wire   [4:0] trunc_ln125_fu_1004_p1;
reg   [4:0] trunc_ln125_reg_1695;
wire   [0:0] trunc_ln125_1_fu_1009_p1;
reg   [0:0] trunc_ln125_1_reg_1700;
reg   [3:0] lshr_ln4_reg_1704;
reg   [3:0] tmp_9_reg_1709;
wire   [0:0] best_fu_1256_p2;
reg   [0:0] best_reg_1819;
wire    ap_CS_fsm_state30;
wire   [0:0] icmp_ln203_fu_1270_p2;
reg   [0:0] icmp_ln203_reg_1824;
reg    fm0_ce0;
wire   [7:0] fm0_q0;
reg    fm0_ce1;
reg    fm0_we1;
reg    fm0_1_ce0;
wire   [7:0] fm0_1_q0;
reg    fm0_1_ce1;
reg    fm0_1_we1;
reg    fm0_2_ce0;
wire   [7:0] fm0_2_q0;
reg    fm0_2_ce1;
reg    fm0_2_we1;
reg    fm0_3_ce0;
wire   [7:0] fm0_3_q0;
reg    fm0_3_ce1;
reg    fm0_3_we1;
reg   [13:0] fm1_address0;
reg    fm1_ce0;
wire   [7:0] fm1_q0;
reg   [13:0] fm1_1_address0;
reg    fm1_1_ce0;
wire   [7:0] fm1_1_q0;
reg   [13:0] fm1_2_address0;
reg    fm1_2_ce0;
wire   [7:0] fm1_2_q0;
reg   [13:0] fm1_3_address0;
reg    fm1_3_ce0;
wire   [7:0] fm1_3_q0;
reg    fm2_ce0;
wire   [7:0] fm2_q0;
reg    fm2_ce1;
reg    fm2_we1;
reg   [12:0] fm3_address0;
reg    fm3_ce0;
wire   [7:0] fm3_q0;
reg   [12:0] fm3_1_address0;
reg    fm3_1_ce0;
wire   [7:0] fm3_1_q0;
reg   [12:0] fm3_2_address0;
reg    fm3_2_ce0;
wire   [7:0] fm3_2_q0;
reg   [12:0] fm3_3_address0;
reg    fm3_3_ce0;
wire   [7:0] fm3_3_q0;
reg    fm4_ce0;
wire   [7:0] fm4_q0;
reg    fm4_ce1;
reg    fm4_we1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_done;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_idle;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_ready;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWVALID;
wire   [63:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWADDR;
wire   [0:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWID;
wire   [31:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWLEN;
wire   [2:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWSIZE;
wire   [1:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWBURST;
wire   [1:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWLOCK;
wire   [3:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWCACHE;
wire   [2:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWPROT;
wire   [3:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWQOS;
wire   [3:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWREGION;
wire   [0:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWUSER;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WVALID;
wire   [31:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WDATA;
wire   [3:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WSTRB;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WLAST;
wire   [0:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WID;
wire   [0:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WUSER;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARVALID;
wire   [63:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARADDR;
wire   [0:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARID;
wire   [31:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARLEN;
wire   [2:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARSIZE;
wire   [1:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARBURST;
wire   [1:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARLOCK;
wire   [3:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARCACHE;
wire   [2:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARPROT;
wire   [3:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARQOS;
wire   [3:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARREGION;
wire   [0:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARUSER;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_RREADY;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_BREADY;
wire   [9:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_address1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_ce1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_we1;
wire   [7:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_d1;
wire   [9:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_address1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_ce1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_we1;
wire   [7:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_d1;
wire   [9:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_address1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_ce1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_we1;
wire   [7:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_d1;
wire   [9:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_address1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_ce1;
wire    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_we1;
wire   [7:0] grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_d1;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_done;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_idle;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_ready;
wire   [13:0] grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_address0;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_ce0;
wire   [13:0] grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_1_address0;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_1_ce0;
wire   [13:0] grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_2_address0;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_2_ce0;
wire   [13:0] grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_3_address0;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_3_ce0;
wire   [13:0] grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_address1;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_ce1;
wire    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_we1;
wire   [7:0] grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_d1;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_done;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_idle;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_ready;
wire   [9:0] grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_address0;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_ce0;
wire   [9:0] grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_1_address0;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_1_ce0;
wire   [9:0] grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_2_address0;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_2_ce0;
wire   [9:0] grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_3_address0;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_3_ce0;
wire   [18:0] grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_acc_2_out;
wire    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_acc_2_out_ap_vld;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_done;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_idle;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_ready;
wire   [12:0] grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_address0;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_ce0;
wire   [12:0] grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_1_address0;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_1_ce0;
wire   [12:0] grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_2_address0;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_2_ce0;
wire   [12:0] grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_3_address0;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_3_ce0;
wire   [12:0] grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_address1;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_ce1;
wire    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_we1;
wire   [7:0] grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_d1;
wire    grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start;
wire    grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_done;
wire    grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_idle;
wire    grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_ready;
wire   [13:0] grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_fm2_address0;
wire    grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_fm2_ce0;
wire   [23:0] grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_acc_8_out;
wire    grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_acc_8_out_ap_vld;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_done;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_idle;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_ready;
wire   [12:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_fm4_address0;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_fm4_ce0;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_64127_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_64127_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_63123_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_63123_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_62119_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_62119_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_61115_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_61115_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_60111_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_60111_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_59107_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_59107_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_58103_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_58103_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5799_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5799_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5695_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5695_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5591_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5591_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5487_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5487_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5383_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5383_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5279_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5279_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5175_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5175_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5071_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5071_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4967_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4967_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4863_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4863_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4759_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4759_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4655_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4655_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4551_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4551_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4447_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4447_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4343_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4343_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4239_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4239_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4135_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4135_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4031_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4031_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3927_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3927_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3823_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3823_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3719_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3719_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3615_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3615_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3511_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3511_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_347_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_347_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_333_out;
wire    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_333_out_ap_vld;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_done;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_idle;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_ready;
wire   [31:0] grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_p_out;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_p_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_291135_out;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_291135_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_087133_out;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_087133_out_ap_vld;
wire   [31:0] grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_189131_out;
wire    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_189131_out_ap_vld;
wire    MBUS_0_AWREADY;
wire    MBUS_0_WREADY;
reg    MBUS_0_ARVALID;
wire    MBUS_0_ARREADY;
reg   [63:0] MBUS_0_ARADDR;
reg   [31:0] MBUS_0_ARLEN;
wire    MBUS_0_RVALID;
reg    MBUS_0_RREADY;
wire   [31:0] MBUS_0_RDATA;
wire   [10:0] MBUS_0_RFIFONUM;
wire    MBUS_0_BVALID;
reg   [6:0] oh_reg_558;
wire   [0:0] icmp_ln76_fu_817_p2;
reg   [6:0] ow_reg_570;
wire   [0:0] icmp_ln75_fu_793_p2;
wire    ap_CS_fsm_state17;
reg   [5:0] oh_1_reg_581;
wire   [0:0] icmp_ln125_fu_992_p2;
reg   [5:0] ow_1_reg_593;
wire   [0:0] icmp_ln124_fu_968_p2;
wire    ap_CS_fsm_state24;
reg    grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start_reg;
wire   [0:0] icmp_ln74_fu_767_p2;
wire    ap_CS_fsm_state18;
reg    grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start_reg;
wire    ap_CS_fsm_state16;
reg    grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start_reg;
wire   [0:0] icmp_ln123_fu_947_p2;
wire    ap_CS_fsm_state25;
reg    grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start_reg;
wire    ap_CS_fsm_state23;
reg    grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start_reg;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
reg    grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start_reg;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire   [63:0] zext_ln74_fu_783_p1;
wire   [63:0] zext_ln95_fu_868_p1;
wire   [63:0] zext_ln123_fu_963_p1;
wire   [63:0] zext_ln143_fu_1043_p1;
wire  signed [63:0] sext_ln50_fu_754_p1;
reg   [4:0] oc_fu_200;
wire    ap_CS_fsm_state31;
reg   [5:0] oc_1_fu_412;
reg    c1_b_ce0_local;
reg    fm1_we0_local;
wire   [7:0] select_ln95_fu_932_p3;
reg    fm1_ce0_local;
reg    fm1_1_we0_local;
reg    fm1_1_ce0_local;
reg    fm1_2_we0_local;
reg    fm1_2_ce0_local;
reg    fm1_3_we0_local;
reg    fm1_3_ce0_local;
reg    c2_b_ce0_local;
reg    fm3_we0_local;
wire   [7:0] select_ln143_fu_1107_p3;
reg    fm3_ce0_local;
reg    fm3_1_we0_local;
reg    fm3_1_ce0_local;
reg    fm3_2_we0_local;
reg    fm3_2_ce0_local;
reg    fm3_3_we0_local;
reg    fm3_3_ce0_local;
wire   [13:0] tmp_s_fu_861_p4;
wire   [9:0] tmp_7_fu_876_p4;
wire   [2:0] tmp_8_fu_892_p4;
wire   [0:0] icmp_ln95_fu_886_p2;
wire   [0:0] icmp_ln96_fu_902_p2;
wire   [0:0] or_ln95_fu_926_p2;
wire   [7:0] select_ln95_1_fu_918_p3;
wire   [7:0] trunc_ln6_fu_908_p4;
wire   [12:0] tmp_1_fu_1036_p4;
wire   [16:0] tmp_10_fu_1051_p4;
wire   [9:0] tmp_11_fu_1067_p4;
wire   [0:0] icmp_ln143_fu_1061_p2;
wire   [0:0] icmp_ln144_fu_1077_p2;
wire   [0:0] or_ln143_fu_1101_p2;
wire   [7:0] select_ln143_1_fu_1093_p3;
wire   [7:0] trunc_ln1_fu_1083_p4;
wire   [31:0] select_ln203_fu_1262_p3;
wire   [1:0] zext_ln201_fu_1279_p1;
wire   [31:0] tmp_2_fu_1289_p7;
wire   [1:0] best_1_fu_1282_p3;
wire   [31:0] tmp_2_fu_1289_p9;
wire   [0:0] icmp_ln204_fu_1306_p2;
wire   [1:0] best_2_fu_1312_p3;
reg   [30:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire   [1:0] tmp_2_fu_1289_p1;
wire   [1:0] tmp_2_fu_1289_p3;
wire  signed [1:0] tmp_2_fu_1289_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
#0 grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start_reg = 1'b0;
#0 grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start_reg = 1'b0;
#0 grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start_reg = 1'b0;
#0 grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start_reg = 1'b0;
#0 grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start_reg = 1'b0;
#0 grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start_reg = 1'b0;
#0 grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start_reg = 1'b0;
#0 oc_fu_200 = 5'd0;
#0 oc_1_fu_412 = 6'd0;
end

cnn_accel_c1_b_ROM_1P_LUTRAM_1R #(
    .DataWidth( 13 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
c1_b_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(c1_b_address0),
    .ce0(c1_b_ce0_local),
    .q0(c1_b_q0)
);

cnn_accel_c2_b_ROM_1P_LUTRAM_1R #(
    .DataWidth( 12 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
c2_b_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(c2_b_address0),
    .ce0(c2_b_ce0_local),
    .q0(c2_b_q0)
);

cnn_accel_fm0_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
fm0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_address0),
    .ce0(fm0_ce0),
    .q0(fm0_q0),
    .address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_address1),
    .ce1(fm0_ce1),
    .we1(fm0_we1),
    .d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_d1)
);

cnn_accel_fm0_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
fm0_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_1_address0),
    .ce0(fm0_1_ce0),
    .q0(fm0_1_q0),
    .address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_address1),
    .ce1(fm0_1_ce1),
    .we1(fm0_1_we1),
    .d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_d1)
);

cnn_accel_fm0_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
fm0_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_2_address0),
    .ce0(fm0_2_ce0),
    .q0(fm0_2_q0),
    .address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_address1),
    .ce1(fm0_2_ce1),
    .we1(fm0_2_we1),
    .d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_d1)
);

cnn_accel_fm0_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
fm0_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_3_address0),
    .ce0(fm0_3_ce0),
    .q0(fm0_3_q0),
    .address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_address1),
    .ce1(fm0_3_ce1),
    .we1(fm0_3_we1),
    .d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_d1)
);

cnn_accel_fm1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fm1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm1_address0),
    .ce0(fm1_ce0),
    .we0(fm1_we0_local),
    .d0(select_ln95_fu_932_p3),
    .q0(fm1_q0)
);

cnn_accel_fm1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fm1_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm1_1_address0),
    .ce0(fm1_1_ce0),
    .we0(fm1_1_we0_local),
    .d0(select_ln95_fu_932_p3),
    .q0(fm1_1_q0)
);

cnn_accel_fm1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fm1_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm1_2_address0),
    .ce0(fm1_2_ce0),
    .we0(fm1_2_we0_local),
    .d0(select_ln95_fu_932_p3),
    .q0(fm1_2_q0)
);

cnn_accel_fm1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fm1_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm1_3_address0),
    .ce0(fm1_3_ce0),
    .we0(fm1_3_we0_local),
    .d0(select_ln95_fu_932_p3),
    .q0(fm1_3_q0)
);

cnn_accel_fm2_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fm2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_fm2_address0),
    .ce0(fm2_ce0),
    .q0(fm2_q0),
    .address1(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_address1),
    .ce1(fm2_ce1),
    .we1(fm2_we1),
    .d1(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_d1)
);

cnn_accel_fm3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
fm3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm3_address0),
    .ce0(fm3_ce0),
    .we0(fm3_we0_local),
    .d0(select_ln143_fu_1107_p3),
    .q0(fm3_q0)
);

cnn_accel_fm3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
fm3_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm3_1_address0),
    .ce0(fm3_1_ce0),
    .we0(fm3_1_we0_local),
    .d0(select_ln143_fu_1107_p3),
    .q0(fm3_1_q0)
);

cnn_accel_fm3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
fm3_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm3_2_address0),
    .ce0(fm3_2_ce0),
    .we0(fm3_2_we0_local),
    .d0(select_ln143_fu_1107_p3),
    .q0(fm3_2_q0)
);

cnn_accel_fm3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
fm3_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(fm3_3_address0),
    .ce0(fm3_3_ce0),
    .we0(fm3_3_we0_local),
    .d0(select_ln143_fu_1107_p3),
    .q0(fm3_3_q0)
);

cnn_accel_fm4_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
fm4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_fm4_address0),
    .ce0(fm4_ce0),
    .q0(fm4_q0),
    .address1(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_address1),
    .ce1(fm4_ce1),
    .we1(fm4_we1),
    .d1(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_d1)
);

cnn_accel_cnn_accel_Pipeline_RD_ROW_RD_COL grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start),
    .ap_done(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_done),
    .ap_idle(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_idle),
    .ap_ready(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_ready),
    .m_axi_MBUS_0_AWVALID(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWVALID),
    .m_axi_MBUS_0_AWREADY(1'b0),
    .m_axi_MBUS_0_AWADDR(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWADDR),
    .m_axi_MBUS_0_AWID(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWID),
    .m_axi_MBUS_0_AWLEN(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWLEN),
    .m_axi_MBUS_0_AWSIZE(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWSIZE),
    .m_axi_MBUS_0_AWBURST(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWBURST),
    .m_axi_MBUS_0_AWLOCK(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWLOCK),
    .m_axi_MBUS_0_AWCACHE(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWCACHE),
    .m_axi_MBUS_0_AWPROT(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWPROT),
    .m_axi_MBUS_0_AWQOS(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWQOS),
    .m_axi_MBUS_0_AWREGION(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWREGION),
    .m_axi_MBUS_0_AWUSER(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_AWUSER),
    .m_axi_MBUS_0_WVALID(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WVALID),
    .m_axi_MBUS_0_WREADY(1'b0),
    .m_axi_MBUS_0_WDATA(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WDATA),
    .m_axi_MBUS_0_WSTRB(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WSTRB),
    .m_axi_MBUS_0_WLAST(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WLAST),
    .m_axi_MBUS_0_WID(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WID),
    .m_axi_MBUS_0_WUSER(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_WUSER),
    .m_axi_MBUS_0_ARVALID(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARVALID),
    .m_axi_MBUS_0_ARREADY(MBUS_0_ARREADY),
    .m_axi_MBUS_0_ARADDR(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARADDR),
    .m_axi_MBUS_0_ARID(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARID),
    .m_axi_MBUS_0_ARLEN(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARLEN),
    .m_axi_MBUS_0_ARSIZE(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARSIZE),
    .m_axi_MBUS_0_ARBURST(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARBURST),
    .m_axi_MBUS_0_ARLOCK(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARLOCK),
    .m_axi_MBUS_0_ARCACHE(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARCACHE),
    .m_axi_MBUS_0_ARPROT(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARPROT),
    .m_axi_MBUS_0_ARQOS(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARQOS),
    .m_axi_MBUS_0_ARREGION(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARREGION),
    .m_axi_MBUS_0_ARUSER(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARUSER),
    .m_axi_MBUS_0_RVALID(MBUS_0_RVALID),
    .m_axi_MBUS_0_RREADY(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_RREADY),
    .m_axi_MBUS_0_RDATA(MBUS_0_RDATA),
    .m_axi_MBUS_0_RLAST(1'b0),
    .m_axi_MBUS_0_RID(1'd0),
    .m_axi_MBUS_0_RFIFONUM(MBUS_0_RFIFONUM),
    .m_axi_MBUS_0_RUSER(1'd0),
    .m_axi_MBUS_0_RRESP(2'd0),
    .m_axi_MBUS_0_BVALID(1'b0),
    .m_axi_MBUS_0_BREADY(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_BREADY),
    .m_axi_MBUS_0_BRESP(2'd0),
    .m_axi_MBUS_0_BID(1'd0),
    .m_axi_MBUS_0_BUSER(1'd0),
    .sext_ln50(trunc_ln_reg_1560),
    .fm0_address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_address1),
    .fm0_ce1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_ce1),
    .fm0_we1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_we1),
    .fm0_d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_d1),
    .fm0_1_address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_address1),
    .fm0_1_ce1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_ce1),
    .fm0_1_we1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_we1),
    .fm0_1_d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_d1),
    .fm0_2_address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_address1),
    .fm0_2_ce1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_ce1),
    .fm0_2_we1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_we1),
    .fm0_2_d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_d1),
    .fm0_3_address1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_address1),
    .fm0_3_ce1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_ce1),
    .fm0_3_we1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_we1),
    .fm0_3_d1(grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_d1)
);

cnn_accel_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start),
    .ap_done(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_done),
    .ap_idle(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_idle),
    .ap_ready(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_ready),
    .fm1_address0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_address0),
    .fm1_ce0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_ce0),
    .fm1_q0(fm1_q0),
    .fm1_1_address0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_1_address0),
    .fm1_1_ce0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_1_ce0),
    .fm1_1_q0(fm1_1_q0),
    .fm1_2_address0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_2_address0),
    .fm1_2_ce0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_2_ce0),
    .fm1_2_q0(fm1_2_q0),
    .fm1_3_address0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_3_address0),
    .fm1_3_ce0(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_3_ce0),
    .fm1_3_q0(fm1_3_q0),
    .fm2_address1(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_address1),
    .fm2_ce1(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_ce1),
    .fm2_we1(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_we1),
    .fm2_d1(grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_d1)
);

cnn_accel_cnn_accel_Pipeline_C1_KY_C1_KX grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start),
    .ap_done(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_done),
    .ap_idle(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_idle),
    .ap_ready(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_ready),
    .sext_ln75(acc_reg_1597),
    .zext_ln75(trunc_ln75_reg_1610),
    .ow(trunc_ln76_reg_1627),
    .fm0_address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_address0),
    .fm0_ce0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_ce0),
    .fm0_q0(fm0_q0),
    .fm0_1_address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_1_address0),
    .fm0_1_ce0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_1_ce0),
    .fm0_1_q0(fm0_1_q0),
    .fm0_2_address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_2_address0),
    .fm0_2_ce0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_2_ce0),
    .fm0_2_q0(fm0_2_q0),
    .fm0_3_address0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_3_address0),
    .fm0_3_ce0(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_3_ce0),
    .fm0_3_q0(fm0_3_q0),
    .zext_ln74_1(trunc_ln74_reg_1579),
    .acc_2_out(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_acc_2_out),
    .acc_2_out_ap_vld(grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_acc_2_out_ap_vld)
);

cnn_accel_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start),
    .ap_done(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_done),
    .ap_idle(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_idle),
    .ap_ready(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_ready),
    .fm3_address0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_address0),
    .fm3_ce0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_ce0),
    .fm3_q0(fm3_q0),
    .fm3_1_address0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_1_address0),
    .fm3_1_ce0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_1_ce0),
    .fm3_1_q0(fm3_1_q0),
    .fm3_2_address0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_2_address0),
    .fm3_2_ce0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_2_ce0),
    .fm3_2_q0(fm3_2_q0),
    .fm3_3_address0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_3_address0),
    .fm3_3_ce0(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_3_ce0),
    .fm3_3_q0(fm3_3_q0),
    .fm4_address1(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_address1),
    .fm4_ce1(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_ce1),
    .fm4_we1(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_we1),
    .fm4_d1(grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_d1)
);

cnn_accel_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start),
    .ap_done(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_done),
    .ap_idle(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_idle),
    .ap_ready(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_ready),
    .sext_ln124(acc_5_reg_1665),
    .zext_ln124(trunc_ln124_reg_1678),
    .zext_ln125(trunc_ln125_reg_1695),
    .fm2_address0(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_fm2_address0),
    .fm2_ce0(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_fm2_ce0),
    .fm2_q0(fm2_q0),
    .oc_1(trunc_ln123_reg_1654),
    .acc_8_out(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_acc_8_out),
    .acc_8_out_ap_vld(grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_acc_8_out_ap_vld)
);

cnn_accel_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start),
    .ap_done(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_done),
    .ap_idle(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_idle),
    .ap_ready(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_ready),
    .fm4_address0(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_fm4_address0),
    .fm4_ce0(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_fm4_ce0),
    .fm4_q0(fm4_q0),
    .gap_64127_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_64127_out),
    .gap_64127_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_64127_out_ap_vld),
    .gap_63123_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_63123_out),
    .gap_63123_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_63123_out_ap_vld),
    .gap_62119_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_62119_out),
    .gap_62119_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_62119_out_ap_vld),
    .gap_61115_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_61115_out),
    .gap_61115_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_61115_out_ap_vld),
    .gap_60111_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_60111_out),
    .gap_60111_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_60111_out_ap_vld),
    .gap_59107_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_59107_out),
    .gap_59107_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_59107_out_ap_vld),
    .gap_58103_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_58103_out),
    .gap_58103_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_58103_out_ap_vld),
    .gap_5799_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5799_out),
    .gap_5799_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5799_out_ap_vld),
    .gap_5695_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5695_out),
    .gap_5695_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5695_out_ap_vld),
    .gap_5591_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5591_out),
    .gap_5591_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5591_out_ap_vld),
    .gap_5487_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5487_out),
    .gap_5487_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5487_out_ap_vld),
    .gap_5383_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5383_out),
    .gap_5383_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5383_out_ap_vld),
    .gap_5279_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5279_out),
    .gap_5279_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5279_out_ap_vld),
    .gap_5175_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5175_out),
    .gap_5175_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5175_out_ap_vld),
    .gap_5071_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5071_out),
    .gap_5071_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5071_out_ap_vld),
    .gap_4967_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4967_out),
    .gap_4967_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4967_out_ap_vld),
    .gap_4863_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4863_out),
    .gap_4863_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4863_out_ap_vld),
    .gap_4759_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4759_out),
    .gap_4759_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4759_out_ap_vld),
    .gap_4655_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4655_out),
    .gap_4655_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4655_out_ap_vld),
    .gap_4551_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4551_out),
    .gap_4551_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4551_out_ap_vld),
    .gap_4447_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4447_out),
    .gap_4447_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4447_out_ap_vld),
    .gap_4343_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4343_out),
    .gap_4343_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4343_out_ap_vld),
    .gap_4239_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4239_out),
    .gap_4239_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4239_out_ap_vld),
    .gap_4135_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4135_out),
    .gap_4135_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4135_out_ap_vld),
    .gap_4031_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4031_out),
    .gap_4031_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4031_out_ap_vld),
    .gap_3927_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3927_out),
    .gap_3927_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3927_out_ap_vld),
    .gap_3823_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3823_out),
    .gap_3823_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3823_out_ap_vld),
    .gap_3719_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3719_out),
    .gap_3719_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3719_out_ap_vld),
    .gap_3615_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3615_out),
    .gap_3615_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3615_out_ap_vld),
    .gap_3511_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3511_out),
    .gap_3511_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3511_out_ap_vld),
    .gap_347_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_347_out),
    .gap_347_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_347_out_ap_vld),
    .gap_333_out(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_333_out),
    .gap_333_out_ap_vld(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_333_out_ap_vld)
);

cnn_accel_cnn_accel_Pipeline_DN_OC_DN_IC grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start),
    .ap_done(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_done),
    .ap_idle(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_idle),
    .ap_ready(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_ready),
    .gap_333_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_333_out),
    .gap_347_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_347_out),
    .gap_3511_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3511_out),
    .gap_3615_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3615_out),
    .gap_3719_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3719_out),
    .gap_3823_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3823_out),
    .gap_3927_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_3927_out),
    .gap_4031_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4031_out),
    .gap_4135_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4135_out),
    .gap_4239_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4239_out),
    .gap_4343_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4343_out),
    .gap_4447_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4447_out),
    .gap_4551_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4551_out),
    .gap_4655_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4655_out),
    .gap_4759_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4759_out),
    .gap_4863_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4863_out),
    .gap_4967_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_4967_out),
    .gap_5071_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5071_out),
    .gap_5175_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5175_out),
    .gap_5279_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5279_out),
    .gap_5383_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5383_out),
    .gap_5487_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5487_out),
    .gap_5591_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5591_out),
    .gap_5695_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5695_out),
    .gap_5799_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_5799_out),
    .gap_58103_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_58103_out),
    .gap_59107_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_59107_out),
    .gap_60111_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_60111_out),
    .gap_61115_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_61115_out),
    .gap_62119_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_62119_out),
    .gap_63123_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_63123_out),
    .gap_64127_reload(grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_gap_64127_out),
    .p_out(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_p_out),
    .p_out_ap_vld(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_p_out_ap_vld),
    .mux_case_291135_out(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_291135_out),
    .mux_case_291135_out_ap_vld(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_291135_out_ap_vld),
    .mux_case_087133_out(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_087133_out),
    .mux_case_087133_out_ap_vld(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_087133_out_ap_vld),
    .mux_case_189131_out(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_189131_out),
    .mux_case_189131_out_ap_vld(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_189131_out_ap_vld)
);

cnn_accel_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .cls_out(cls_out),
    .cls_out_ap_vld(cls_out_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cnn_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_bram(in_bram)
);

cnn_accel_MBUS_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 256 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MBUS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MBUS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MBUS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MBUS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MBUS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MBUS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MBUS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MBUS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MBUS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MBUS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MBUS_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 4 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 4 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
MBUS_m_axi_U(
    .AWVALID(m_axi_MBUS_AWVALID),
    .AWREADY(m_axi_MBUS_AWREADY),
    .AWADDR(m_axi_MBUS_AWADDR),
    .AWID(m_axi_MBUS_AWID),
    .AWLEN(m_axi_MBUS_AWLEN),
    .AWSIZE(m_axi_MBUS_AWSIZE),
    .AWBURST(m_axi_MBUS_AWBURST),
    .AWLOCK(m_axi_MBUS_AWLOCK),
    .AWCACHE(m_axi_MBUS_AWCACHE),
    .AWPROT(m_axi_MBUS_AWPROT),
    .AWQOS(m_axi_MBUS_AWQOS),
    .AWREGION(m_axi_MBUS_AWREGION),
    .AWUSER(m_axi_MBUS_AWUSER),
    .WVALID(m_axi_MBUS_WVALID),
    .WREADY(m_axi_MBUS_WREADY),
    .WDATA(m_axi_MBUS_WDATA),
    .WSTRB(m_axi_MBUS_WSTRB),
    .WLAST(m_axi_MBUS_WLAST),
    .WID(m_axi_MBUS_WID),
    .WUSER(m_axi_MBUS_WUSER),
    .ARVALID(m_axi_MBUS_ARVALID),
    .ARREADY(m_axi_MBUS_ARREADY),
    .ARADDR(m_axi_MBUS_ARADDR),
    .ARID(m_axi_MBUS_ARID),
    .ARLEN(m_axi_MBUS_ARLEN),
    .ARSIZE(m_axi_MBUS_ARSIZE),
    .ARBURST(m_axi_MBUS_ARBURST),
    .ARLOCK(m_axi_MBUS_ARLOCK),
    .ARCACHE(m_axi_MBUS_ARCACHE),
    .ARPROT(m_axi_MBUS_ARPROT),
    .ARQOS(m_axi_MBUS_ARQOS),
    .ARREGION(m_axi_MBUS_ARREGION),
    .ARUSER(m_axi_MBUS_ARUSER),
    .RVALID(m_axi_MBUS_RVALID),
    .RREADY(m_axi_MBUS_RREADY),
    .RDATA(m_axi_MBUS_RDATA),
    .RLAST(m_axi_MBUS_RLAST),
    .RID(m_axi_MBUS_RID),
    .RUSER(m_axi_MBUS_RUSER),
    .RRESP(m_axi_MBUS_RRESP),
    .BVALID(m_axi_MBUS_BVALID),
    .BREADY(m_axi_MBUS_BREADY),
    .BRESP(m_axi_MBUS_BRESP),
    .BID(m_axi_MBUS_BID),
    .BUSER(m_axi_MBUS_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(MBUS_0_ARVALID),
    .I_CH0_ARREADY(MBUS_0_ARREADY),
    .I_CH0_ARADDR(MBUS_0_ARADDR),
    .I_CH0_ARLEN(MBUS_0_ARLEN),
    .I_CH0_RVALID(MBUS_0_RVALID),
    .I_CH0_RREADY(MBUS_0_RREADY),
    .I_CH0_RDATA(MBUS_0_RDATA),
    .I_CH0_RFIFONUM(MBUS_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(MBUS_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(MBUS_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(MBUS_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U116(
    .din0(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_087133_out),
    .din1(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_189131_out),
    .din2(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_291135_out),
    .def(tmp_2_fu_1289_p7),
    .sel(best_1_fu_1282_p3),
    .dout(tmp_2_fu_1289_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln76_fu_817_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
            grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_ready == 1'b1)) begin
            grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln125_fu_992_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
            grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_ready == 1'b1)) begin
            grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state28)) begin
            grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_ready == 1'b1)) begin
            grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state26)) begin
            grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_ready == 1'b1)) begin
            grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln74_fu_767_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
            grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_ready == 1'b1)) begin
            grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln123_fu_947_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_ready == 1'b1)) begin
            grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_ready == 1'b1)) begin
            grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln74_fu_767_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        oc_1_fu_412 <= 6'd0;
    end else if (((icmp_ln124_fu_968_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        oc_1_fu_412 <= add_ln123_reg_1649;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        oc_fu_200 <= 5'd0;
    end else if (((icmp_ln75_fu_793_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        oc_fu_200 <= add_ln74_reg_1574;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln125_fu_992_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        oh_1_reg_581 <= add_ln124_reg_1673;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        oh_1_reg_581 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln76_fu_817_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        oh_reg_558 <= add_ln75_reg_1605;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        oh_reg_558 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ow_1_reg_593 <= add_ln125_reg_1690;
    end else if (((icmp_ln124_fu_968_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        ow_1_reg_593 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ow_reg_570 <= add_ln76_reg_1622;
    end else if (((icmp_ln75_fu_793_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        ow_reg_570 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        acc_5_reg_1665 <= c2_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        acc_reg_1597 <= c1_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln123_reg_1649 <= add_ln123_fu_953_p2;
        trunc_ln123_reg_1654 <= trunc_ln123_fu_959_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        add_ln124_reg_1673 <= add_ln124_fu_974_p2;
        trunc_ln124_1_reg_1683 <= trunc_ln124_1_fu_984_p1;
        trunc_ln124_reg_1678 <= trunc_ln124_fu_980_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        add_ln125_reg_1690 <= add_ln125_fu_998_p2;
        lshr_ln4_reg_1704 <= {{ow_1_reg_593[4:1]}};
        tmp_9_reg_1709 <= {{oh_1_reg_581[4:1]}};
        trunc_ln125_1_reg_1700 <= trunc_ln125_1_fu_1009_p1;
        trunc_ln125_reg_1695 <= trunc_ln125_fu_1004_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln74_reg_1574 <= add_ln74_fu_773_p2;
        trunc_ln74_reg_1579 <= trunc_ln74_fu_779_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln75_reg_1605 <= add_ln75_fu_799_p2;
        trunc_ln75_1_reg_1615 <= trunc_ln75_1_fu_809_p1;
        trunc_ln75_reg_1610 <= trunc_ln75_fu_805_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln76_reg_1622 <= add_ln76_fu_823_p2;
        lshr_ln3_reg_1636 <= {{ow_reg_570[5:1]}};
        tmp_reg_1641 <= {{oh_reg_558[5:1]}};
        trunc_ln76_1_reg_1632 <= trunc_ln76_1_fu_834_p1;
        trunc_ln76_reg_1627 <= trunc_ln76_fu_829_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        best_reg_1819 <= best_fu_1256_p2;
        icmp_ln203_reg_1824 <= icmp_ln203_fu_1270_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_1560 <= {{in_bram[63:2]}};
    end
end

always @ (*) begin
    if (((1'b1 == MBUS_0_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        MBUS_0_ARADDR = sext_ln50_fu_754_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        MBUS_0_ARADDR = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARADDR;
    end else begin
        MBUS_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == MBUS_0_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        MBUS_0_ARLEN = 64'd1024;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        MBUS_0_ARLEN = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARLEN;
    end else begin
        MBUS_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == MBUS_0_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        MBUS_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        MBUS_0_ARVALID = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_ARVALID;
    end else begin
        MBUS_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        MBUS_0_RREADY = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_m_axi_MBUS_0_RREADY;
    end else begin
        MBUS_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        MBUS_blk_n_AR = m_axi_MBUS_ARREADY;
    end else begin
        MBUS_blk_n_AR = 1'b1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_done == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_done == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == MBUS_0_ARREADY)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        c1_b_ce0_local = 1'b1;
    end else begin
        c1_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        c2_b_ce0_local = 1'b1;
    end else begin
        c2_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        cls_out_ap_vld = 1'b1;
    end else begin
        cls_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fm0_1_ce0 = grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_1_ce0;
    end else begin
        fm0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_1_ce1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_ce1;
    end else begin
        fm0_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_1_we1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_1_we1;
    end else begin
        fm0_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fm0_2_ce0 = grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_2_ce0;
    end else begin
        fm0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_2_ce1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_ce1;
    end else begin
        fm0_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_2_we1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_2_we1;
    end else begin
        fm0_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fm0_3_ce0 = grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_3_ce0;
    end else begin
        fm0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_3_ce1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_ce1;
    end else begin
        fm0_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_3_we1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_3_we1;
    end else begin
        fm0_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fm0_ce0 = grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_fm0_ce0;
    end else begin
        fm0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_ce1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_ce1;
    end else begin
        fm0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm0_we1 = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_fm0_we1;
    end else begin
        fm0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_1_address0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_1_address0;
    end else begin
        fm1_1_address0 = zext_ln95_fu_868_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_1_ce0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_1_ce0;
    end else begin
        fm1_1_ce0 = fm1_1_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        fm1_1_ce0_local = 1'b1;
    end else begin
        fm1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (trunc_ln76_1_reg_1632 == 1'd1) & (trunc_ln75_1_reg_1615 == 1'd0))) begin
        fm1_1_we0_local = 1'b1;
    end else begin
        fm1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_2_address0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_2_address0;
    end else begin
        fm1_2_address0 = zext_ln95_fu_868_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_2_ce0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_2_ce0;
    end else begin
        fm1_2_ce0 = fm1_2_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        fm1_2_ce0_local = 1'b1;
    end else begin
        fm1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (trunc_ln76_1_reg_1632 == 1'd0) & (trunc_ln75_1_reg_1615 == 1'd1))) begin
        fm1_2_we0_local = 1'b1;
    end else begin
        fm1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_3_address0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_3_address0;
    end else begin
        fm1_3_address0 = zext_ln95_fu_868_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_3_ce0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_3_ce0;
    end else begin
        fm1_3_ce0 = fm1_3_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        fm1_3_ce0_local = 1'b1;
    end else begin
        fm1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (trunc_ln76_1_reg_1632 == 1'd1) & (trunc_ln75_1_reg_1615 == 1'd1))) begin
        fm1_3_we0_local = 1'b1;
    end else begin
        fm1_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_address0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_address0;
    end else begin
        fm1_address0 = zext_ln95_fu_868_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm1_ce0 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm1_ce0;
    end else begin
        fm1_ce0 = fm1_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        fm1_ce0_local = 1'b1;
    end else begin
        fm1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (trunc_ln76_1_reg_1632 == 1'd0) & (trunc_ln75_1_reg_1615 == 1'd0))) begin
        fm1_we0_local = 1'b1;
    end else begin
        fm1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        fm2_ce0 = grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_fm2_ce0;
    end else begin
        fm2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm2_ce1 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_ce1;
    end else begin
        fm2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        fm2_we1 = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_fm2_we1;
    end else begin
        fm2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_1_address0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_1_address0;
    end else begin
        fm3_1_address0 = zext_ln143_fu_1043_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_1_ce0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_1_ce0;
    end else begin
        fm3_1_ce0 = fm3_1_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        fm3_1_ce0_local = 1'b1;
    end else begin
        fm3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln125_1_reg_1700 == 1'd1) & (trunc_ln124_1_reg_1683 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        fm3_1_we0_local = 1'b1;
    end else begin
        fm3_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_2_address0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_2_address0;
    end else begin
        fm3_2_address0 = zext_ln143_fu_1043_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_2_ce0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_2_ce0;
    end else begin
        fm3_2_ce0 = fm3_2_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        fm3_2_ce0_local = 1'b1;
    end else begin
        fm3_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln125_1_reg_1700 == 1'd0) & (trunc_ln124_1_reg_1683 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        fm3_2_we0_local = 1'b1;
    end else begin
        fm3_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_3_address0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_3_address0;
    end else begin
        fm3_3_address0 = zext_ln143_fu_1043_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_3_ce0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_3_ce0;
    end else begin
        fm3_3_ce0 = fm3_3_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        fm3_3_ce0_local = 1'b1;
    end else begin
        fm3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln125_1_reg_1700 == 1'd1) & (trunc_ln124_1_reg_1683 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        fm3_3_we0_local = 1'b1;
    end else begin
        fm3_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_address0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_address0;
    end else begin
        fm3_address0 = zext_ln143_fu_1043_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm3_ce0 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm3_ce0;
    end else begin
        fm3_ce0 = fm3_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        fm3_ce0_local = 1'b1;
    end else begin
        fm3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln125_1_reg_1700 == 1'd0) & (trunc_ln124_1_reg_1683 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        fm3_we0_local = 1'b1;
    end else begin
        fm3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        fm4_ce0 = grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_fm4_ce0;
    end else begin
        fm4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm4_ce1 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_ce1;
    end else begin
        fm4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        fm4_we1 = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_fm4_we1;
    end else begin
        fm4_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == MBUS_0_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln74_fu_767_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln75_fu_793_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln76_fu_817_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln123_fu_947_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((icmp_ln124_fu_968_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((icmp_ln125_fu_992_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state25 : begin
            if (((grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_fu_953_p2 = (oc_1_fu_412 + 6'd1);

assign add_ln124_fu_974_p2 = (oh_1_reg_581 + 6'd1);

assign add_ln125_fu_998_p2 = (ow_1_reg_593 + 6'd1);

assign add_ln74_fu_773_p2 = (oc_fu_200 + 5'd1);

assign add_ln75_fu_799_p2 = (oh_reg_558 + 7'd1);

assign add_ln76_fu_823_p2 = (ow_reg_570 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign best_1_fu_1282_p3 = ((icmp_ln203_reg_1824[0:0] == 1'b1) ? 2'd2 : zext_ln201_fu_1279_p1);

assign best_2_fu_1312_p3 = ((icmp_ln204_fu_1306_p2[0:0] == 1'b1) ? 2'd3 : best_1_fu_1282_p3);

assign best_fu_1256_p2 = (($signed(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_189131_out) > $signed(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_087133_out)) ? 1'b1 : 1'b0);

assign c1_b_address0 = zext_ln74_fu_783_p1;

assign c2_b_address0 = zext_ln123_fu_963_p1;

assign cls_out = best_2_fu_1312_p3;

assign grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start = grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_ap_start_reg;

assign grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start = grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_ap_start_reg;

assign grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start = grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_ap_start_reg;

assign grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start = grp_cnn_accel_Pipeline_GAP_IC_GAP_H_GAP_W_fu_660_ap_start_reg;

assign grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start = grp_cnn_accel_Pipeline_P1_IC_P1_OH_P1_OW_fu_615_ap_start_reg;

assign grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start = grp_cnn_accel_Pipeline_P2_IC_P2_OH_P2_OW_fu_639_ap_start_reg;

assign grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start = grp_cnn_accel_Pipeline_RD_ROW_RD_COL_fu_604_ap_start_reg;

assign icmp_ln123_fu_947_p2 = ((oc_1_fu_412 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_968_p2 = ((oh_1_reg_581 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_992_p2 = ((ow_1_reg_593 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln143_fu_1061_p2 = (($signed(tmp_10_fu_1051_p4) < $signed(17'd1)) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_1077_p2 = (($signed(tmp_11_fu_1067_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln203_fu_1270_p2 = (($signed(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_291135_out) > $signed(select_ln203_fu_1262_p3)) ? 1'b1 : 1'b0);

assign icmp_ln204_fu_1306_p2 = (($signed(grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_p_out) > $signed(tmp_2_fu_1289_p9)) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_767_p2 = ((oc_fu_200 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_793_p2 = ((oh_reg_558 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_817_p2 = ((ow_reg_570 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_886_p2 = (($signed(tmp_7_fu_876_p4) < $signed(10'd1)) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_902_p2 = (($signed(tmp_8_fu_892_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign or_ln143_fu_1101_p2 = (icmp_ln144_fu_1077_p2 | icmp_ln143_fu_1061_p2);

assign or_ln95_fu_926_p2 = (icmp_ln96_fu_902_p2 | icmp_ln95_fu_886_p2);

assign select_ln143_1_fu_1093_p3 = ((icmp_ln143_fu_1061_p2[0:0] == 1'b1) ? 8'd0 : 8'd127);

assign select_ln143_fu_1107_p3 = ((or_ln143_fu_1101_p2[0:0] == 1'b1) ? select_ln143_1_fu_1093_p3 : trunc_ln1_fu_1083_p4);

assign select_ln203_fu_1262_p3 = ((best_fu_1256_p2[0:0] == 1'b1) ? grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_189131_out : grp_cnn_accel_Pipeline_DN_OC_DN_IC_fu_697_mux_case_087133_out);

assign select_ln95_1_fu_918_p3 = ((icmp_ln95_fu_886_p2[0:0] == 1'b1) ? 8'd0 : 8'd127);

assign select_ln95_fu_932_p3 = ((or_ln95_fu_926_p2[0:0] == 1'b1) ? select_ln95_1_fu_918_p3 : trunc_ln6_fu_908_p4);

assign sext_ln50_fu_754_p1 = $signed(trunc_ln_reg_1560);

assign tmp_10_fu_1051_p4 = {{grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_acc_8_out[23:7]}};

assign tmp_11_fu_1067_p4 = {{grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_acc_8_out[23:14]}};

assign tmp_1_fu_1036_p4 = {{{trunc_ln123_reg_1654}, {tmp_9_reg_1709}}, {lshr_ln4_reg_1704}};

assign tmp_2_fu_1289_p7 = 'bx;

assign tmp_7_fu_876_p4 = {{grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_acc_2_out[18:9]}};

assign tmp_8_fu_892_p4 = {{grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_acc_2_out[18:16]}};

assign tmp_s_fu_861_p4 = {{{trunc_ln74_reg_1579}, {tmp_reg_1641}}, {lshr_ln3_reg_1636}};

assign trunc_ln123_fu_959_p1 = oc_1_fu_412[4:0];

assign trunc_ln124_1_fu_984_p1 = oh_1_reg_581[0:0];

assign trunc_ln124_fu_980_p1 = oh_1_reg_581[4:0];

assign trunc_ln125_1_fu_1009_p1 = ow_1_reg_593[0:0];

assign trunc_ln125_fu_1004_p1 = ow_1_reg_593[4:0];

assign trunc_ln1_fu_1083_p4 = {{grp_cnn_accel_Pipeline_C2_KY_C2_KX_C2_IC_fu_648_acc_8_out[14:7]}};

assign trunc_ln6_fu_908_p4 = {{grp_cnn_accel_Pipeline_C1_KY_C1_KX_fu_624_acc_2_out[16:9]}};

assign trunc_ln74_fu_779_p1 = oc_fu_200[3:0];

assign trunc_ln75_1_fu_809_p1 = oh_reg_558[0:0];

assign trunc_ln75_fu_805_p1 = oh_reg_558[5:0];

assign trunc_ln76_1_fu_834_p1 = ow_reg_570[0:0];

assign trunc_ln76_fu_829_p1 = ow_reg_570[5:0];

assign zext_ln123_fu_963_p1 = oc_1_fu_412;

assign zext_ln143_fu_1043_p1 = tmp_1_fu_1036_p4;

assign zext_ln201_fu_1279_p1 = best_reg_1819;

assign zext_ln74_fu_783_p1 = oc_fu_200;

assign zext_ln95_fu_868_p1 = tmp_s_fu_861_p4;

endmodule //cnn_accel
