// =========================================================================================
// Module : dbwfb2_97_bram_ctrl
// Purpose: Natively Aligned & Boundary-Extended Block RAM (BRAM) Memory Controller.
//
// Detailed Structural Mechanics:
//   This controller schedules reads and writes between a dual-port external BRAM matrix 
//   and the 9/7 wavelet convolution core. It resolves two primary hardware edge cases:
//
//   1. Latency & Group Delay Alignment: 
//      A 9-tap filter requires its internal shift registers to be completely packed with 
//      legitimate image data before producing valid mathematical coefficients. The FSM 
//      implements a 'pipe_fill' delay gate that suppresses memory writes for the first 
//      9 clock cycles, aligning output index 0 with the exact center tap of the filter window.
//
//   2. Constant Boundary Extension (Edge Smoothing):
//      When input sample streams terminate, filtering a finite image edge creates a numerical
//      "cliff" if padded with zeros, causing artificial high-frequency ringing and corrupting
//      the subband energy metrics. This module captures the final valid pixel into a register 
//      ('last_pixel') and replicates it during the FLUSH phase, mimicking a zero-overhead, 
//      clamped boundary padding scheme that ensures smooth mathematical derivatives.
//
// LPF-ONLY PACKING:
//   ob_din = {{16{y_lpf[15]}}, y_lpf}  (sign-extended 32-bit word):
//     bits [15:0]  → y_lpf  (LL subband, 16-bit signed)
//     bits [31:16] → sign extension of y_lpf[15]
//
//   WHY SIGN-EXTEND rather than zero-pad:
//     y_lpf is a 2's-complement signed 16-bit value. Sign-extension to 32 bits
//     preserves the numerical value correctly. If any downstream logic (PS DMA,
//     AXI-BRAM read, future debug) ever interprets the full 32-bit word as a
//     signed integer it will read the exact same value. Zero-padding would corrupt
//     negative coefficients. The CNN read path (conv1_pe) reads only [15:0] so the
//     upper half is harmless padding either way - but sign-extension is strictly
//     correct and costs nothing in hardware.
//
//   The output BRAM stays at 32-bit width (AXI BRAM Controller mode, unchanged).
//   Bit-width migration to 16-bit (True Dual Port / standalone mode) is deferred
//   to the CNN integration phase.
// =========================================================================================
module dbwfb2_97_bram_ctrl #(
    parameter ADDR_W = 16,    // Structural address bus width for handling deep image dimensions
    parameter DATA_W = 16     // Bit-width of individual color/pixel components (Signed 16-bit)
)(
    input  wire                clk,
    input  wire                rst_n,

    // --- System Control and Status Interface ---
    input  wire                start,       // Pulsed high to trigger execution of a 1D processing stream
    input  wire [ADDR_W-1:0]   pixel_count, // Total active elements per row/column (e.g., 256)
    output reg                 done,        // Asserted high when output data sequence is completely saved

    // --- Input BRAM Port B (Source Read Interface) - 32-BIT Bus Wide ---
    output reg  [31:0]         ib_addr,     // Generated byte/word read address
    output reg                 ib_en,       // Read block RAM enable strobe
    input  wire [31:0]         ib_dout,     // Dual-packed input data returned from memory execution

    // --- Output BRAM Port B (Destination Write Interface) - 32-BIT Bus Wide ---
    output reg  [31:0]         ob_addr,     // Generated byte/word write destination address
    output reg                 ob_en,       // Write block RAM chip enable strobe
    output reg  [3:0]          ob_we,       // Byte-lane write enables (4'b1111 for full 32-bit word save)
    // ob_din packing: bits[15:0] = y_lpf (LL subband), bits[31:16] = sign extension
    output wire [31:0]         ob_din
);

    // ---- Pipeline register between BRAM memory boundaries and the conv module ----
    // Stores the current active sample to decouple raw memory output routing latencies.
    reg signed [DATA_W-1:0] xin_reg; 

    // ---- Boundary extension tracking logic ----
    // Captures the absolute final valid pixel sample of the current row or column line.
    reg signed [DATA_W-1:0] last_pixel;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) 
            last_pixel <= 16'sd0;
        else if (state == FLUSH && flush_cnt == 4'd0)
            last_pixel <= $signed(ib_dout[15:0]); // Snapshot the edge pixel boundary
    end

    // ---- Boundary Condition Multiplexer (Edge-Noise Elimination) ----
    wire flush_mode;
    wire signed [DATA_W-1:0] xin_mux = (state == FLUSH && flush_cnt > 4'd0) ? last_pixel : $signed(ib_dout[15:0]);

    always @(posedge clk or negedge rst_n)
        if (!rst_n) xin_reg <= 16'sd0;
        else        xin_reg <= xin_mux;

    // ---- Convolution Sub-core Integration ----
    // LPF-only path.
    wire signed [DATA_W-1:0] y_lpf;

    dbwfb2_97_conv u_conv (
        .clk   (clk),
        .rst_n (rst_n),
        .xin   (xin_reg),
        .y_lpf (y_lpf)
    );

    // ---- Output BRAM word packing ----
    // Sign-extend 16-bit signed y_lpf to fill the 32-bit BRAM word.
    // Upper 16 bits = sign extension of y_lpf[15]; lower 16 bits = y_lpf.
    // CNN read path (conv1_pe) uses only bits[15:0].
    assign ob_din = {{16{y_lpf[15]}}, y_lpf};

    // ---- Finite State Machine (FSM) Parametrization ----
    localparam IDLE  = 3'd0;
    localparam PROC  = 3'd1;
    localparam FLUSH = 3'd2;
    localparam DONE  = 3'd3;

    reg [2:0]          state;
    reg [ADDR_W-1:0]   rd_cnt;
    reg [ADDR_W-1:0]   wr_cnt;
    reg [3:0]          flush_cnt;
    reg [3:0]          pipe_fill;

    assign flush_mode = (state == FLUSH);

    // ---- Primary FSM and Memory Address Scheduling Block ----
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= IDLE;
            done      <= 1'b0;
            rd_cnt    <= 0;
            wr_cnt    <= 0;
            flush_cnt <= 0;
            pipe_fill <= 0;
            ib_addr   <= 0;  
            ib_en     <= 1'b0;
            ob_addr   <= 0;  
            ob_en     <= 1'b0;  
            ob_we     <= 4'b0000; 
        end else begin
            case (state)

                IDLE: begin
                    done      <= 1'b0;
                    rd_cnt    <= 0;
                    wr_cnt    <= 0;
                    flush_cnt <= 0;
                    pipe_fill <= 0;
                    ib_en     <= 1'b0;
                    ob_en     <= 1'b0;
                    ob_we     <= 4'b0000; 
                    ib_addr   <= 0;
                    ob_addr   <= 0;

                    if (start) begin
                        state   <= PROC;
                        ib_en   <= 1'b1;
                        ib_addr <= 0;
                    end
                end

                PROC: begin
                    // 1. Read Processing Address Path Engine
                    if (rd_cnt < pixel_count - 1) begin
                        rd_cnt  <= rd_cnt + 1;
                        ib_addr <= ((rd_cnt + 1) << 2); 
                        ib_en   <= 1'b1;
                    end else begin
                        ib_en   <= 1'b0;
                    end

                    // 2. Write Processing Path (9-cycle group delay gate)
                    if (pipe_fill < 4'd9) begin
                        pipe_fill <= pipe_fill + 1;
                        ob_en     <= 1'b0;
                        ob_we     <= 4'b0000; 
                    end else begin
                        if (wr_cnt < pixel_count) begin
                            ob_en   <= 1'b1;
                            ob_we   <= 4'b1111;
                            ob_addr <= (wr_cnt << 2);
                            wr_cnt  <= wr_cnt + 1;
                        end
                    end

                    // 3. Transition to FLUSH when all input pixels have been read
                    if (rd_cnt >= pixel_count - 1) begin
                        state     <= FLUSH;
                        flush_cnt <= 0;
                    end
                end

                FLUSH: begin
                    ib_en     <= 1'b0;
                    flush_cnt <= flush_cnt + 1;

                    if (wr_cnt < pixel_count) begin
                        ob_en   <= 1'b1;
                        ob_we   <= 4'b1111; 
                        ob_addr <= (wr_cnt << 2);
                        wr_cnt  <= wr_cnt + 1;
                    end else begin
                        ob_en   <= 1'b0;
                        ob_we   <= 4'b0000; 
                    end

                    if (wr_cnt >= pixel_count) begin   
                        ob_en <= 1'b0;
                        ob_we <= 4'b0000; 
                        state <= DONE;
                    end
                end

                DONE: begin
                    done  <= 1'b1;
                    ob_en <= 1'b0;
                    ob_we <= 4'b0000; 
                    ib_en <= 1'b0;
                    
                    if (!start) state <= IDLE;
                end

                default: state <= IDLE;
            endcase
        end
    end
endmodule
