// =========================================================================================
// Module : dbwfb2_97_bram_ctrl
// Purpose: Natively Aligned & Boundary-Extended Block RAM (BRAM) Memory Controller.
//
// Detailed Structural Mechanics:
//   This controller schedules reads and writes between a dual-port external BRAM matrix 
//   and the 9/7 wavelet convolution core. It resolves two primary hardware edge cases:
//
//   1. Latency & Group Delay Alignment: 
//      A 9-tap filter requires its internal shift registers to be completely packed with 
//      legitimate image data before producing valid mathematical coefficients. The FSM 
//      implements a 'pipe_fill' delay gate that suppresses memory writes for the first 
//      9 clock cycles, aligning output index 0 with the exact center tap of the filter window.
//
//   2. Constant Boundary Extension (Edge Smoothing):
//      When input sample streams terminate, filtering a finite image edge creates a numerical
//      "cliff" if padded with zeros, causing artificial high-frequency ringing and corrupting
//      the subband energy metrics. This module captures the final valid pixel into a register 
//      ('last_pixel') and replicates it during the FLUSH phase, mimicking a zero-overhead, 
//      clamped boundary padding scheme that ensures smooth mathematical derivatives.
// =========================================================================================
module dbwfb2_97_bram_ctrl #(
    parameter ADDR_W = 16,    // Structural address bus width for handling deep image dimensions
    parameter DATA_W = 16     // Bit-width of individual color/pixel components (Signed 16-bit)
)(
    input  wire                clk,
    input  wire                rst_n,

    // --- System Control and Status Interface ---
    input  wire                start,       // Pulsed high to trigger execution of a 1D processing stream
    input  wire [ADDR_W-1:0]   pixel_count, // Total active elements per row/column (e.g., 256)
    output reg                 done,        // Asserted high when output data sequence is completely saved

    // --- Input BRAM Port B (Source Read Interface) - 32-BIT Bus Wide ---
    output reg  [31:0]         ib_addr,     // Generated byte/word read address
    output reg                 ib_en,       // Read block RAM enable strobe
    input  wire [31:0]         ib_dout,     // Dual-packed input data returned from memory execution

    // --- Output BRAM Port B (Destination Write Interface) - 32-BIT Bus Wide ---
    output reg  [31:0]         ob_addr,     // Generated byte/word write destination address
    output reg                 ob_en,       // Write block RAM chip enable strobe
    output reg  [3:0]          ob_we,       // Byte-lane write enables (4'b1111 for full 32-bit word save)
    output wire [31:0]         ob_din       // Interleaved composite stream packed as {y_hpf, y_lpf}
);

    // ---- Pipeline register between BRAM memory boundaries and the conv module ----
    // Stores the current active sample to decouple raw memory output routing latencies.
    reg signed [DATA_W-1:0] xin_reg; 

    // ---- Boundary extension tracking logic ----
    // Captures the absolute final valid pixel sample of the current row or column line.
    // Timing Criticality: When the FSM shifts from PROC to FLUSH, 'rd_cnt' has just 
    // completed its sweep. Because BRAM read latency takes 1-2 clock cycles, the absolute last 
    // valid pixel word settles on the 'ib_dout' bus precisely at (state == FLUSH && flush_cnt == 0).
    reg signed [DATA_W-1:0] last_pixel;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) 
            last_pixel <= 16'sd0;
        else if (state == FLUSH && flush_cnt == 4'd0)
            last_pixel <= $signed(ib_dout[15:0]); // Snapshot the edge pixel boundary
    end

    // ---- Boundary Condition Multiplexer (Edge-Noise Elimination) ----
    // Dynamically switches data paths during pipeline draining. 
    // - PROC Mode: Passes live, sequential pixel data streaming out of the source BRAM.
    // - FLUSH Mode (flush_cnt > 0): Halts memory reads and clamps the convolution input to 
    //   'last_pixel'. This eliminates high-frequency noise leakage and edge spectral explosion 
    //   by maintaining a smooth constant plateau while the filter pipeline flushes.
    wire flush_mode;
    wire signed [DATA_W-1:0] xin_mux = (state == FLUSH && flush_cnt > 4'd0) ? last_pixel : $signed(ib_dout[15:0]);

    always @(posedge clk or negedge rst_n)
        if (!rst_n) xin_reg <= 16'sd0;
        else        xin_reg <= xin_mux;

    // ---- Convolution Sub-core Integration ----
    // Passes the managed, boundary-extended sample stream directly into the shift-add tree.
    wire signed [DATA_W-1:0] y_lpf, y_hpf;

    dbwfb2_97_conv u_conv (
        .clk   (clk),
        .rst_n (rst_n),
        .xin   (xin_reg),
        .y_lpf (y_lpf),
        .y_hpf (y_hpf)
    );

    // Interleave and pack the resulting low-pass and high-pass coefficients into a unified 
    // 32-bit BRAM word wrapper. Fits natively into dual-packed memory spaces.
    assign ob_din = {y_hpf, y_lpf}; 

    // ---- Finite State Machine (FSM) Parametrization ----
    localparam IDLE  = 3'd0; // Quiescent state: rests until master system issues a 'start' command.
    localparam PROC  = 3'd1; // Main execution loop: handles parallel streaming reads and pipeline priming.
    localparam FLUSH = 3'd2; // Boundary extension state: replicates edge pixels to clear pipeline data.
    localparam DONE  = 3'd3; // Completion handshake state: signals master, waits for 'start' de-assertion.

    reg [2:0]          state;
    reg [ADDR_W-1:0]   rd_cnt;     // Tracks individual active read address iterations up to 'pixel_count'
    reg [ADDR_W-1:0]   wr_cnt;     // Tracks active write operations written to destination memory
    reg [3:0]          flush_cnt;  // Manages internal clock cycles spent in the FLUSH state loop
    reg [3:0]          pipe_fill;  // 4-bit alignment register counting out the initial group-delay latency

    assign flush_mode = (state == FLUSH);

    // ---- Primary FSM and Memory Address Scheduling Block ----
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= IDLE;
            done      <= 1'b0;
            rd_cnt    <= 0;
            wr_cnt    <= 0;
            flush_cnt <= 0;
            pipe_fill <= 0;
            ib_addr   <= 0;  
            ib_en     <= 1'b0;
            ob_addr   <= 0;  
            ob_en     <= 1'b0;  
            ob_we     <= 4'b0000; 
        end else begin
            case (state)

                IDLE: begin
                    done      <= 1'b0;
                    rd_cnt    <= 0;
                    wr_cnt    <= 0;
                    flush_cnt <= 0;
                    pipe_fill <= 0;
                    ib_en     <= 1'b0;
                    ob_en     <= 1'b0;
                    ob_we     <= 4'b0000; 
                    ib_addr   <= 0;
                    ob_addr   <= 0;

                    if (start) begin
                        state   <= PROC;
                        ib_en   <= 1'b1;
                        ib_addr <= 0; // Target index 0 on initial execution trigger
                    end
                end

                PROC: begin
                    // 1. Read Processing Address Path Engine
                    // Generates word-aligned sequential read sweeps. Addresses are left-shifted by 2
                    // (<< 2) to translate linear indices into 32-bit (4-byte) physical BRAM addresses.
                    if (rd_cnt < pixel_count - 1) begin
                        rd_cnt  <= rd_cnt + 1;
                        ib_addr <= ((rd_cnt + 1) << 2); 
                        ib_en   <= 1'b1;
                    end else begin
                        ib_en   <= 1'b0; // Terminate reads immediately when maximum boundaries are reached
                    end

                    // 2. Write Processing Path (Calibrated to 9-cycle filter group delay latency)
                    // Suppresses destination writes for the first 9 clock periods while the 
                    // convolution delay chain initializes. This guarantees that uninitialized or stale 
                    // registers cannot leak garbage values into the beginning of the output BRAM matrix.
                    if (pipe_fill < 4'd9) begin
                        pipe_fill <= pipe_fill + 1;
                        ob_en     <= 1'b0;
                        ob_we     <= 4'b0000; 
                    end else begin
                        if (wr_cnt < pixel_count) begin
                            ob_en   <= 1'b1;
                            ob_we   <= 4'b1111; // Enable all 4 byte-lanes for full 32-bit write
                            ob_addr <= (wr_cnt << 2); // Physical 32-bit word byte alignment scaling
                            wr_cnt  <= wr_cnt + 1;
                        end
                    end

                    // 3. State Transition Boundary Rules
                    // Transitions to the FLUSH state when all core data elements have been read out.
                    if (rd_cnt >= pixel_count - 1) begin
                        state     <= FLUSH;
                        flush_cnt <= 0;
                    end
                end

                FLUSH: begin
                    ib_en     <= 1'b0; // Explicitly lock read operations to protect memory integrity
                    flush_cnt <= flush_cnt + 1;

                    // Continues calculating and storing valid coefficients still caught inside the 
                    // processing pipelines, while relying on 'xin_mux' to substitute the edge padding.
                    if (wr_cnt < pixel_count) begin
                        ob_en   <= 1'b1;
                        ob_we   <= 4'b1111; 
                        ob_addr <= (wr_cnt << 2);
                        wr_cnt  <= wr_cnt + 1;
                    end else begin
                        ob_en   <= 1'b0;
                        ob_we   <= 4'b0000; 
                    end

                    // Safe Deterministic Exit Mechanism:
                    // Guarantees that the controller does not exit based on an arbitrary cycle count.
                    // Instead, it monitors 'wr_cnt' and transitions to DONE the exact clock edge 
                    // after writing the final output coefficient, dropping write enables to zero.
                    if (wr_cnt >= pixel_count) begin   
                        ob_en <= 1'b0;
                        ob_we <= 4'b0000; 
                        state <= DONE;
                    end
                end

                DONE: begin
                    done  <= 1'b1; // Raise status flag to notify host processor / downstream modules
                    ob_en <= 1'b0;
                    ob_we <= 4'b0000; 
                    ib_en <= 1'b0;
                    
                    // Simple asynchronous handshake response: return to IDLE once master system 
                    // acknowledges processing completion by pulling the 'start' line low.
                    if (!start) state <= IDLE;
                end

                default: state <= IDLE;
            endcase
        end
    end
endmodule